#ifndef _LANG_VIEWER_H_
#define _LANG_VIEWER_H_

#include "Language.h"

//language resource 
 
#define		ID_STR_OK							10001	//确定
#define		ID_STR_EXIT							10002	//退出
#define		ID_STR_CANCEL						10003	//取消
#define		ID_STR_CHANNEL						10004	//通道
#define		ID_STR_TITLE						10005	//CMS Client
#define		ID_STR_MAP							10006	//地图窗口
#define		ID_STR_VIEW							10007	//视频窗口
#define		ID_STR_VIEW_MAP						10008	//视频\地图
#define		ID_STR_NAVIGATE						10009	//导航面板
#define		ID_STR_SAVE_SUC						10010	//保存成功
#define		ID_STR_EVENT						10011	//事件面板
#define		ID_STR_CONFIRM_DELETE				10012	//数据删除后将不可恢复！是否删除？
#define		ID_STR_SELECT_FOLDER				10013	//选择路径
#define		ID_STR_CAR_CENTER					10014	//以车辆为中心
#define		ID_STR_SELECT_DEVICE				10015	//选择车辆
#define		ID_STR_SNAPSHOT						10016	//抓拍图片
#define		ID_STR_VOLUME						10017	//音量控制
#define		ID_STR_SELECT_DEV_EMPTY				10018	//请选择一个车辆结点，或者车辆通道结点！
#define		ID_STR_PANE_PLAY					10019	//搜索面板
#define		ID_STR_VIEW_POP						10020	//独立视频窗口
#define		ID_STR_VIEW_TITLE					10021	//视频窗口
#define		ID_STR_READY						10022	//就绪
#define		ID_STR_MAP_VIEW						10023	//地图\视频
#define		ID_STR_PANE_TRACK					10024	//搜索面板
#define     ID_STR_MONITOR                      10025   //监控
#define     ID_STR_STATISTIC                    10026   //统计
#define     ID_STR_CMS_LOGINPASSWORD            10027   //(CMS登录密码)
#define		ID_STR_YES							10028	//是
#define		ID_STR_NO							10029	//否
#define		ID_STR_ADD_SUCCESS					10030	//添加成功
#define		ID_STR_DEL_SUCCESS					10031	//删除成功
#define		ID_STR_SAVING						10032	//正在保存...
#define		ID_STR_SNAPSHOT_MENU				10033	//抓拍

#define		ID_STR_PRIVILIDEG_USR_MGR			10051	//用户管理
#define		ID_STR_PRIVILIDEG_DEVICE_MGR		10052	//设备管理
#define		ID_STR_PRIVILIDEG_MEDIA_MGR			10053	//流媒体管理（流媒体服务器、转发配置）
#define		ID_STR_PRIVILIDEG_RECORD_MGR		10054	//存储管理（存储服务器、存储配置、录像计划）
#define		ID_STR_PRIVILIDEG_ALARM_SVR			10055	//报警管理
#define		ID_STR_PRIVILIDEG_MAP_MGR			10056	//电子地图管理
#define		ID_STR_PRIVILIDEG_MATRIX_MGR		10057	//电视墙管理
#define		ID_STR_PRIVILIDEG_DEV_PARA_SETUP	10058	//设备参数管理
#define		ID_STR_PRIVILIDEG_ALARM_MGR			10059	//报警联动管理
#define		ID_STR_PRIVILIDEG_PREVIEW			10060	//视频预览
#define		ID_STR_PRIVILIDEG_VOICE_COM			10061	//双向对讲
#define		ID_STR_PRIVILIDEG_SNAPSHOT			10062	//前端抓拍
#define		ID_STR_PRIVILIDEG_RECORD_PLAYBACK	10063	//远程回放
#define		ID_STR_PRIVILIDEG_PTZ_CTRL			10064	//云台控制
#define		ID_STR_PRIVILIDEG_LOG_QUERY			10065	//日志查询

//////////////////////////////////////////////////////////////////////////
//hw 2013/1/16
#define		ID_STR_PRIVILIDEG_NO_RIGHT			10081	//用户无权限
//////////////////////////////////////////////////////////////////////////

#define		ID_STR_DLG_LOGIN_ST_USER			10101	//用户
#define		ID_STR_DLG_LOGIN_ST_PWD				10102	//密码
#define		ID_STR_DLG_LOGIN_BTN_LOGIN			10103	//登录
#define		ID_STR_DLG_LOGIN_ST_SVRIP			10107	//服务器
#define		ID_STR_DLG_LOGIN_TIP_USER_EMPTY		10108	//用户名信息有误，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_PWD_EMPTY		10109	//密码不得为空，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_SVRIP_EMPTY	10110	//服务器地址有误，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_USER_NO_EXIST	10113	//用户不存在，请重新输入用户信息！
#define		ID_STR_DLG_LOGIN_TIP_PWD_ERROR		10114	//密码错误，请重新输入密码信息！
#define		ID_STR_DLG_LOGIN_TITLE				10115	//登录
#define		ID_STR_DLG_LOGIN_TIP_INPUT			10116	//请输入用户名及服务器信息
#define		ID_STR_DLG_LOGIN_TIP_LOGINING		10117	//正在登录系统，请等待.......
#define		ID_STR_DLG_LOGIN_TIP_USR_ERR		10118	//用户名有误，请重新输入
#define		ID_STR_DLG_LOGIN_TIP_PWD_ERR		10119	//密码有误，请重新输入
#define		ID_STR_DLG_LOGIN_TIP_CNT_ERR		10120	//无法连接服务器，请重新输入
#define		ID_STR_DLG_LOGIN_TIP_CNT_SUC		10121	//登录成功,程序加载中,请稍后...
#define		ID_STR_DLG_LOGIN_TIP_FULL_ERR		10122	//服务器用户满！请过段时间后登录！
#define		ID_STR_DLG_LOGIN_TIP_LOADING_INFO	10123	//正在服务器获取信息，请等待......
#define		ID_STR_DLG_LOGIN_TIP_LOADING_FD		10124	//获取信息失败！请重试！
#define		ID_STR_DLG_LOGIN_RELOGIN_TITLE		10125	//重新登录
#define		ID_STR_DLG_LOGIN_TIP_VER_ERR		10127	//版本信息不匹配，请使用最新版本客户端！
#define		ID_STR_DLG_LOGIN_TIP_EXIST			10128	//用户已登录
#define		ID_STR_DLG_LOGIN_ST_COMPANY			10129	//公司
#define		ID_STR_DLG_LOGIN_TIP_CMP_ERR		10130	//公司信息有误，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_USER_DEL		10131	//用户已删除，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_USER_EXPIRED	10132	//用户已过期，请重新输入！
#define		ID_STR_DLG_LOGIN_TIP_UPGRADE		10133	//软件必须升级后才能继续使用！是否升级？
#define     ID_STR_DLG_LOGIN_TIP                10134   //请输入用户名信息
#define		ID_STR_DLG_LOGIN_UPGRADE_LEASTEST	10135	//升级到最新版本
#define		ID_STR_DLG_LOGIN_UPGRADE_NEXTTIME	10136	//下次再进行升级
#define		ID_STR_DLG_LOGIN_UPGRADE_HIGHEST	10137	//客户端版本比服务器版本高，从网站上重新下载安装包？
#define		ID_STR_DLG_LOGIN_UPGRADE_TITLE		10138	//客户端升级提示
#define     ID_STR_DLG_LOGIN_SAVE_PSW			10139   //记住密码
#define     ID_STR_DLG_LOGIN_AUTO_LOGIN			10140   //自动登录

#define		ID_STR_MODIFY_ERROR				10525	//操作失败！错误原因：
#define		ID_STR_MODIFY_NET_ERR			10526	//网络错误
#define		ID_STR_MODIFY_RIGHT_ERR			10527	//用户无权限
#define		ID_STR_MODIFY_PARAM_ERR			10528	//参数错误
#define		ID_STR_MODIFY_DB_ERR			10529	//操作数据库失败
#define		ID_STR_MODIFY_NAME_USED			10530	//名称已被占用
#define		ID_STR_MODIFY_NO_EXIST			10531	//信息不存在
#define		ID_STR_MODIFY_ADMIN_ERR			10532	//管理员组不得编辑
#define		ID_STR_MODIFY_GROUP_USED		10533	//用户组还被占用
#define		ID_STR_MODIFY_UNKNOWN			10534	//未知错误
#define		ID_STR_MODIFY_IDNO_USED			10535	//序列号已经被占用
#define		ID_STR_MODIFY_SVR_EMPTY			10536	//服务器信息不存在
#define		ID_STR_MODIFY_SVR_DIS_ONLINE	10537	//服务器不在线
#define		ID_STR_MODIFY_OBJ_NO_EXIST		10538	//地图不存在相应的对象信息
#define		ID_STR_MODIFY_MAP_USED			10539	//地图信息正被使用
#define		ID_STR_MODIFY_OBJ_DEFINDED		10540	//对象信息已在地图上标识，不允许重复标识
#define		ID_STR_MODIFY_USR_NO_EXIST		10541	//用户不存在
#define		ID_STR_MODIFY_DEV_NO_EXIST		10542	//设备信息不存在
#define		ID_STR_MODIFY_MAP_NO_EXIST		10543	//地图不存在
#define		ID_STR_MODIFY_DEV_DIS_ONLINE	10544	//设备不在线
#define		ID_STR_MODIFY_DEV_NO_RESP		10545	//没有收到设备的回应
#define		ID_STR_MODIFY_CNT_DS_FAILED		10546	//中心服务器连接失败
#define		ID_STR_MODIFY_CNT_MS_FD			10547	//连接流媒体转发服务器失败
#define		ID_STR_MODIFY_MSVR_EMPTY		10548	//未定义流媒体转发服务器
#define		ID_STR_MODIFY_MS_DOWNING		10550	//流媒体转发服务器正在响应其它客户端的请求，请过会重试！
#define		ID_STR_MODIFY_MS_DISCONNECT		10551	//与流媒体转发服务器网络连接中断
#define		ID_STR_MODIFY_MS_TIMEOUT		10552	//获取数据超时
#define		ID_STR_MODIFY_MS_UPLOADING		10553	//流媒体转发服务器正在响应其它客户端的上传请求，请过会重试！
#define		ID_STR_MODIFY_DEV_DUEING		10554	//正在与其它客户端进行对讲
#define		ID_STR_MODIFY_DEV_TRAN_MSVR_EMPTY	10555	//未定义监控服务器的转发服务器地址信息
#define		ID_STR_MODIFY_DEV_ENT_FAILED	10556	//与监控服务器连接中断
#define		ID_STR_MODIFY_CNT_MS_SUC		10557	//连接流媒体服务器成功
#define		ID_STR_MODIFY_DEV_REC_POS_EMPTY	10558	//没有为车辆指定存储服务器进行数据存储！
#define		ID_STR_MODIFY_RSVR_DISONLINE	10559	//存储服务器不在线，无法连接存储服务器！
#define		ID_STR_MODIFY_RSVR_CNT_FIALED	10560	//存储服务器连接中断
#define		ID_STR_MODIFY_FILE_EXT_ERR		10561	//文件格式错误
#define		ID_STR_MODIFY_FILE_NO_EXIST		10562	//服务器上不存在此文件	
#define		ID_STR_MODIFY_FILE_DOWN_OK		10563	//文件已全部下载完成
#define		ID_STR_MODIFY_FILE_DOWN_ING		10564	//文件正在下载
#define		ID_STR_MODIFY_CREATE_TEMP_FILE	10565	//创建临时文件失败！
#define		ID_STR_MODIFY_MTX_WND_LARGER	10566	//窗口序号错误！电视墙拥有的窗口数目比此序号小！
#define		ID_STR_MODIFY_MTX_DEVICE_USED	10567	//解码器设备已经在其它窗口上定义！
#define		ID_STR_MODIFY_ALARMSVR_SUPPORT_ONE	10568	//系统只支持单个报警服务器！
#define		ID_STR_MODIFY_SERVICE_UNVALID	10569	//系统资源限制，请过会重试！
#define		ID_STR_MODIFY_CNT_LS_FD			10570	//连接接入服务器失败
#define		ID_STR_MODIFY_MS_DEV_FULL		10571	//媒体服务器支持限制
#define		ID_STR_MODIFY_SESSION_EXIST		10572	//设备会话信息已经存在
#define     ID_STR_MODIFY_SESSION_LIMIT		10573	///设备会话数目限制
#define		ID_STR_MODIFY_SRV_NO_RESP		10574	//服务器无响应
#define		ID_STR_MODIFY_FILE_USED			10575	//文件被占用
#define		ID_STR_MODIFY_DISK_ERR			10576	//磁盘满，无法再写入文件

#define		ID_STR_DLG_PANE_DEVICE			11001	//终端列表
#define		ID_STR_DLG_CONTRL_ALL_GROUP			11003	//所有分组
#define		ID_STR_DLG_PANE_PLAY			11004	//远程回放
#define		ID_STR_DLG_PANE_CAM				11005	//镜头控制
#define		ID_STR_DLG_PANE_BCAST			11006	//对讲及广播
#define		ID_STR_DLG_PANE_DEV_AREA_LIST		11007	//场地列表
#define		ID_STR_TRAINING					11008		//训练场
#define		ID_STR_EXAMINATION				11009		//考场
#define		ID_STR_AREA_DEV					11010		//场地设备
#define		ID_STR_DEV_LIST					11011		//车辆列表
#define		ID_STR_CAR						11012		//车辆

#define		ID_STR_DLG_VIEW_REQ_ING				16001	//正在获取视频...
#define		ID_STR_DLG_VIEW_REQ_SUC				16002	//请求视频成功
#define		ID_STR_DLG_VIEW_CNT_DS_FD			16003	//连接目录服务器失败！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_REQ_USR_NORIGHT		16004	//用户无权限查看设备视频！
#define		ID_STR_DLG_VIEW_REQ_MS_EMPTY		16005	//获取流媒体服务器信息失败！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_REQ_CNT_MS_FD		16006	//连接流媒体服务失败！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_START_VIEW			16007	//开始预览
#define		ID_STR_DLG_VIEW_STOP_VIEW			16008	//停止预览
#define		ID_STR_DLG_VIEW_START_POLLING		16009	//开始轮询
#define		ID_STR_DLG_VIEW_STOP_POLLING		16010	//停止轮询
#define		ID_STR_DLG_VIEW_START_AUDIO			16011	//打开声音
#define		ID_STR_DLG_VIEW_STOP_AUDIO			16012	//关闭声音
#define		ID_STR_DLG_VIEW_CAPTURE				16013	//抓拍图片
#define		ID_STR_DLG_VIEW_FULL_SCREEN			16014	//全屏显示
#define		ID_STR_DLG_VIEW_START_DUE			16015	//开始对讲
#define		ID_STR_DLG_VIEW_STOP_DUE			16016	//停止对讲
#define		ID_STR_DLG_VIEW_SETUP				16017	//预览设置
#define		ID_STR_DLG_VIEW_DEV_SETUP			16018	//参数设置
#define		ID_STR_DLG_VIEW_BAR_WND				16019	//窗口
#define		ID_STR_DLG_VIEW_START_ALL			16020	//开启所有预览
#define		ID_STR_DLG_VIEW_STOP_ALL			16021	//停止所有预览
#define		ID_STR_DLG_VIEW_POLLING_ALL			16022	//开启所有轮询
#define		ID_STR_DLG_VIEW_STOP_POLLING_ALL	16023	//停止所有轮询
#define		ID_STR_DLG_VIEW_WND_1				16024	//1画面
#define		ID_STR_DLG_VIEW_WND_4				16025	//4画面
#define		ID_STR_DLG_VIEW_WND_9				16026	//9画面
#define		ID_STR_DLG_VIEW_WND_16				16027	//16画面
#define		ID_STR_DLG_VIEW_REQ_CNT_MS_SUC		16028	//连接流媒体服务成功！请等待...
#define		ID_STR_DLG_VIEW_REQ_CNT_DEV_FD		16029	//向设备请求视频失败！请等待...
#define		ID_STR_DLG_VIEW_REQ_CNT_DEV_SUC		16030	//向设备请求视频成功！请等待...
#define		ID_STR_DLG_VIEW_REQ_DISCNT			16031	//视频连接中断！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_REQ_USR_FULL		16032	//向设备请求视频成功！请等待...
#define		ID_STR_DLG_VIEW_REQ_USR_ERROR		16033	//视频连接用户已满！
#define		ID_STR_DLG_VIEW_REQ_USR_UNKNOW		16034	//视频连接用户不存在！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_REQ_UNKNOW			16035	//未知错误！正在重新请求，请等待...
#define		ID_STR_DLG_VIEW_INTO_DIV			16036	//进入视频切割
#define		ID_STR_DLG_VIEW_EXIT_DIV			16037	//退出视频切割
#define		ID_STR_DLG_VIEW_CLOSE_DIV			16038	//关闭视频
#define		ID_STR_DLG_VIEW_IA_SETUP			16039	//智能分析设置
#define		ID_STR_DLG_VIEW_IA_SHOW				16040	//智能分析预览
#define		ID_STR_DLG_VIEW_STOP_PLAY			16041	//停止播放
#define		ID_STR_DLG_VIEW_PLAY_PAUSE			16042	//播放//暂停
#define		ID_STR_DLG_VIEW_PLAY_FAST			16043	//快进
#define		ID_STR_DLG_VIEW_PLAY_SLOW			16044	//慢放
#define		ID_STR_DLG_VIEW_PLAY_CAPTURE		16045	//抓拍图片
#define		ID_STR_DLG_VIEW_PLAY_STEP			16046	//单帧进
#define		ID_STR_DLG_VIEW_DEV_PREVIEWING		16047	//正在预览此通道视频信息！
#define		ID_STR_DLG_VIEW_BUFFER_ING			16048	//视频缓存中......
#define		ID_STR_DLG_VIEW_PLAY_FAILED			16049	//回放失败！错误原因：
#define		ID_STR_DLG_VIEW_VIEW_MAIN_STREAM	16050	//预览主码流
#define		ID_STR_DLG_VIEW_VIEW_SUB_STREAM		16051	//预览子码流
#define		ID_STR_DLG_VIEW_VIEW_DRAG_VIEW		16052	//拖动预览码流设置
#define		ID_STR_DLG_VIEW_VIEW_DBCLK_VIEW		16053	//双击预览码流设置
#define		ID_STR_DLG_VIEW_MAIN_STREAM			16054	//主码流
#define		ID_STR_DLG_VIEW_SUB_STREAM			16055	//子码流
#define		ID_STR_MENU_SHOW_ALARM				16056	//查看最新报警
#define		ID_STR_MENU_CONFIRM_ALARM			16057	//确认报警信息
#define		ID_STR_MENU_QUERY_ALARM				16058	//查询报警信息
#define		ID_STR_DLG_VIEW_WND_UP				16059	//向上移动窗口
#define		ID_STR_DLG_VIEW_WND_DOWN			16060	//向下移动窗口
#define		ID_STR_DLG_VIEW_ADD_BCAST			16061	//加入广播队列
#define		ID_STR_DLG_VIEW_START_BCAST			16062	//开始广播
#define		ID_STR_DLG_VIEW_DEL_BCAST			16063	//退出广播队列
#define		ID_STR_MENU_START_VEHI_RUN			16064	//开启实时监控
#define		ID_STR_MENU_STOP_VEHI_RUN			16065	//停止实时监控
#define		ID_STR_MENU_START_MONITOR			16066	//开始监听
#define		ID_STR_MENU_STOP_MONITOR			16067	//停止监听	
#define		ID_STR_MENU_START_VIDEORECORD		16068	//开始录像
#define		ID_STR_MENU_STOP_VIDEORECORD		16069	//停止录像	
#define		ID_STR_MENU_DISCONNECT_OIL			16070	//断开油路
#define		ID_STR_MENU_CONNECT_OIL				16071	//打开油路
#define		ID_STR_MENU_TURNOFF_POWER			16072	//关闭电源
#define		ID_STR_MENU_TURNON_POWER			16073	//打开电源	
#define		ID_STR_MENU_RESTART_DEV				16074	//重启设备
#define		ID_STR_MENU_FACTORY_SETTING			16075	//恢复出厂设置	
#define		ID_STR_MENU_SEND_TEXT				16076	//TTS语音
#define		ID_STR_MENU_BROWSE_REC_FILE			16077	//浏览录像文件
#define		ID_STR_MENU_DEV_INFO				16078	//车辆信息
#define		ID_STR_MENU_EQUIPMENT_PROMOTE		16079	//设备升级
#define     ID_STR_MENU_DEV_PARAMER_CONF        16080   //设备参数配置
#define     ID_STR_DLG_VIEW_VIDIO               16081   //视频
#define		ID_STR_DLG_VIEW_WND_6				16082	//6画面
#define		ID_STR_DLG_VIEW_WND_8				16083	//8画面

#define		ID_STR_MENU_DISCONNECT_OIL_SUC		16084	//断开油路设置成功
#define		ID_STR_MENU_CONNECT_OIL_SUC			16085	//打开油路设置成功
#define		ID_STR_MENU_TURNOFF_POWER_SUC		16086	//关闭电源设置成功
#define		ID_STR_MENU_TURNON_POWER_SUC		16087	//打开电源设置成功	
#define		ID_STR_MENU_RESTART_DEV_SUC			16088	//重启设备设置成功
#define		ID_STR_MENU_FACTORY_SETTING_SUC		16089	//恢复出厂设置成功
#define		ID_STR_MENU_DISCONNECT_OIL_F		16090	//断开油路设置失败
#define		ID_STR_MENU_CONNECT_OIL_F			16091	//打开油路设置失败
#define		ID_STR_MENU_TURNOFF_POWER_F			16092	//关闭电源设置失败
#define		ID_STR_MENU_TURNON_POWER_F			16093	//打开电源设置失败	
#define		ID_STR_MENU_RESTART_DEV_F			16094	//重启设备设置失败
#define		ID_STR_MENU_FACTORY_SETTING_F		16095	//恢复出厂设置失败
#define		ID_STR_MENU_START_ALL_RECORD		16096	//开启所有录像
#define		ID_STR_MENU_STOP_ALL_RECORD			16097	//关闭所有录像
#define		ID_STR_MENU_START_PICTURE			16098	//开启图片预览
#define		ID_STR_MENU_STOP_PICTURE			16099	//开启图片预览

#define		ID_STR_DLG_VIEW_MGR_ST_WND			16101	//预览窗口
#define		ID_STR_DLG_VIEW_MGR_WINDOW			16102	//窗口
#define		ID_STR_DLG_VIEW_MGR_ST_POLLING		16103	//轮询列表
#define		ID_STR_DLG_VIEW_MGR_ST_TYPE			16104	//预览类型
#define		ID_STR_DLG_VIEW_MGR_ST_TIME			16105	//轮询时长
#define		ID_STR_DLG_VIEW_MGR_ST_TM_RANGE		16106	//(15~300秒)
#define		ID_STR_DLG_VIEW_MGR_TYPE_MAIN		16107	//主码流
#define		ID_STR_DLG_VIEW_MGR_TYPE_SUB		16108	//从码流
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_DEV	16109	//设备
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_CHAN	16110	//通道
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_TYPE	16111	//类型
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_TIME	16112	//时间
#define		ID_STR_DLG_VIEW_MGR_TIP_TIME_ERR	16113	//轮询时长范围有误
#define		ID_STR_DLG_VIEW_MGR_TIP_NODE_EXIST	16114	//已经存在同一设备同一通道的信息
#define		ID_STR_DLG_VIEW_MGR_TIP_POLLING_ERR	16115	//窗口正在轮询，请停止轮询后再进行操作！是否停止轮询？
#define		ID_STR_DLG_VIEW_MGR_BTN_UP			16116	//上
#define		ID_STR_DLG_VIEW_MGR_BTN_DOWN		16117	//下
#define		ID_STR_DLG_VIEW_MGR_TITLE			16118	//视频轮询设置
#define     ID_STR_DLG_VIEW_MGR_POLLING_NEW     16119   //正在轮询 - 
#define     ID_STR_DLG_VIEW_SHOW_TITLE		    16120   //显示标题
#define     ID_STR_DLG_VIEW_HIDE_TITLE		    16121   //隐藏标题 

#define		ID_STR_DLG_SHOW_SYSTEM_WND			19986	//显示系统窗口
#define		ID_STR_DLG_HIDE_SYSTEM_WND			19987	//隐藏系统窗口
#define		ID_STR_DLG_EVENT_HIDE_RIGHT_WND		19988	//隐藏右侧窗口
#define		ID_STR_DLG_EVENT_SHOW_RIGHT_WND		19989	//显示右侧窗口
#define		ID_STR_DLG_EVENT_HIDE_EVEN_PANE		19990	//最小化事件面板
#define		ID_STR_DLG_EVENT_SHOW_EVEN_PANE		19991	//显示事件面板

#define		ID_STR_DLG_EVENT_RUNINT_ACC_OFF_0	19992	//停车未熄火
#define		ID_STR_DLG_EVENT_RUNINT_ALARM_0		19993	//报警
#define		ID_STR_DLG_EVENT_RUNINT_OFFLINE_0	19994	//离线
#define		ID_STR_DLG_EVENT_RUNINT_DEV_0		19995	//正在运行

#define		ID_STR_DLG_EVENT_RUNINT_ACC_OFF		19996	//停车未熄火的车辆
#define		ID_STR_DLG_EVENT_RUNINT_ALARM		19997	//报警的车辆
#define		ID_STR_DLG_EVENT_RUNINT_OFFLINE		19998	//离线的车辆
#define		ID_STR_DLG_EVENT_RUNINT_DEV			19999	//正在运行的车辆
#define		ID_STR_DLG_EVENT_LST_OTHER_INFO		20000	//其他信息
#define		ID_STR_DLG_EVENT_LST_ALARM_TIME		20001	//时间
#define		ID_STR_DLG_EVENT_LST_ALARM_TYPE		20002	//类型
#define		ID_STR_DLG_EVENT_LST_ALARM_INFO		20004	//内容
#define		ID_STR_DLG_EVENT_MENU_CLEAR			20005	//清空事件
#define		ID_STR_DLG_EVENT_LST_REAL_VEHI		20006	//车辆
#define		ID_STR_DLG_EVENT_LST_REAL_SPEED		20007	//速度
#define		ID_STR_DLG_EVENT_LST_REAL_LONG		20008	//经度
#define		ID_STR_DLG_EVENT_LST_REAL_LAT		20009	//纬度
#define		ID_STR_DLG_EVENT_LST_REAL_TIME		20010	//GPS时间
#define		ID_STR_DLG_EVENT_LST_REAL_RV_TIME	20011	//接收时间
#define		ID_STR_DLG_EVENT_LST_REAL_ONLINE	20012	//在线
#define		ID_STR_DLG_EVENT_LST_REAL_STATUS	20013	//状态
#define		ID_STR_DLG_EVENT_LST_REAL_CONFIRM	20014	//处理状态
#define		ID_STR_DLG_EVENT_LST_INFO_TIME		20015	//时间
#define		ID_STR_DLG_EVENT_LST_INFO_TYPE		20016	//类型
#define		ID_STR_DLG_EVENT_LST_INFO_INFO		20017	//内容
#define		ID_STR_DLG_EVENT_LST_REAL_MAP		20018	//地图显示
#define		ID_STR_MENU_VEHI_RUN_STOP			20019	//停止实时监控
#define		ID_STR_MENU_VEHI_RUN_CLEAR			20020	//清除实时监控
#define		ID_STR_MENU_VEHI_MAP				20021	//实时跟踪车辆
#define		ID_STR_MENU_VEHI_MAP_DEL			20022	//取消跟踪车辆
#define		ID_STR_MENU_VEHI_MAP_CENTER			20023	//以车辆为中心
#define		ID_STR_MENU_VEHI_DEL_CENTER			20024	//取消车辆为中心
#define		ID_STR_CHANGE_TO_MAP_VIEW			20025	//当前处于视频预览界面！是否切换到电子地图界面进行位置显示？
#define		ID_STR_MENU_ALARM_UNVERIFY			20026	//查看未确认报警
#define		ID_STR_MENU_ALARM_MAP				20027	//地图显示报警
#define		ID_STR_MENU_ALARM_QUERY				20028	//查询更多报警
#define		ID_STR_MENU_ALARM_CLEAR				20029	//清空报警
#define		ID_STR_EVENT_LIST_ALRM_NOCONFRIM	20030	//未处理报警
#define		ID_STR_EVENT_LIST_ALRM_CONFRIMED	20031	//已处理报警
#define		ID_STR_EVENT_LIST_ALRM_NONEED		20032	//无需处理
#define		ID_STR_MENU_ALARM_MAP_CLEAR			20033	//地图清除报警
#define		ID_STR_DEV							20034	//终端
#define		ID_STR_DLG_EVENT_AUTO_SORT			20035	//自动排序

#define		ID_STR_DLG_EVENT_TAB_REAL			20041	//GPS监控
#define		ID_STR_DLG_EVENT_TAB_ALARM			20042	//报警信息
#define		ID_STR_DLG_EVENT_TAB_INFO			20043	//系统事件

#define		ID_STR_MOBILE_DEV_SEX				20050	//性别
#define		ID_STR_MOBILE_DEV_ID_CAR			20051	//身份证
#define		ID_STR_MOBILE_DEV_USER_NUM			20052	//编号
#define		ID_STR_MOBILE_DEV_POST				20053	//职务

#define		ID_STR_MOBILE_DEV_EQUIP				20055	//装备
#define		ID_STR_MOBILE_DEV_ADDRESS			20056	//住址
#define		ID_STR_MOBILE_DEV_GROUP				20057	//所属队名

#define		ID_STR_MOBILE_DEV_TEAM_LEADER		20060	//队长
#define		ID_STR_MOBILE_DEV_TEAM_MEMBER		20061	//队员
#define		ID_STR_MOBILE_DEV_SEX_MAN			20062	//男
#define		ID_STR_MOBILE_DEV_SEX_WOMAN			20063	//女


#define		ID_STR_VEHI_RUN_FULL				20071	//地图上最多显示%d车。是否进行替换显示？
#define		ID_STR_TEMPERATOR_DEVICE			20072	//设备温度
#define		ID_STR_TEMPERATOR_MOTER				20073	//发动机温度
#define		ID_STR_TEMPERATOR_COACH				20074	//车厢温度
#define		ID_STR_VEHI_REAL_FULL				20075	//系统已经同时跟踪%d辆车！不允许再增加车辆跟踪！
#define		ID_STR_VEHI_DIRECTION				20076	//方向：
#define		ID_STR_NORTH						20077	//北
#define		ID_STR_NORTH_EAST					20078	//东北
#define		ID_STR_EAST							20079	//东
#define		ID_STR_SOUTH_EAST					20080	//东南
#define		ID_STR_SOUTH						20081	//南
#define		ID_STR_SOUTH_WEST					20082	//西南
#define		ID_STR_WEST							20083	//西
#define		ID_STR_NORTH_WEST					20084	//西北
#define		ID_STR_DIRECTION_INVALID			20085	//无效	

#define		ID_STR_DLG_TABCK_BROAD_ERR			21001	//正在进行广播，无法再进行对讲操作！
#define		ID_STR_DLG_TABCK_OPEN_ERR			21002	//开启对讲失败！系统无麦克输入设备，或者麦克已被其它程序占用！
#define		ID_STR_DLG_TABCK_DEV_DUEING			21003	//设备已经在对讲！不允许重复添加！
#define		ID_STR_DLG_TABCK_LST_DEV			21004	//对讲车辆
#define		ID_STR_DLG_TABCK_LST_STATUS			21005	//对讲状态
#define		ID_STR_DLG_TABCK_LST_GROUP			21006	//所属分组
#define		ID_STR_DLG_TABCK_DEV_REQING			21007	//正在请求对讲.....
#define		ID_STR_DLG_TABCK_ING				21008	//对讲中......
#define		ID_STR_DLG_TABCK_MENU_STOP			21009	//停止对讲
#define		ID_STR_DLG_TABCK_MENU_STOP_ALL		21010	//停止全部
#define		ID_STR_DLG_TABCK_GROUP_NAME			21011	//组名

#define		ID_STR_DLG_DOWNLOAD_TITLE			24001	//正在从设备获取数据
#define		ID_STR_DLG_DOWNLOAD_SNAPSHOT		24002	//正在从设备获取抓拍数据，请等待......
#define		ID_STR_DLG_DOWNLOAD_GETALLCFG		24003	//正在从设备获取所有参数，请等待......
#define		ID_STR_DLG_DOWNLOAD_DOWN_FAILED		24004	//获取数据失败！
#define		ID_STR_DLG_DOWNLOAD_DOWNING			24005	//正在向服务器请求数据，请等待......

#define		ID_STR_DLG_UPLOAD_TITLE				25001	//正在从设备获取数据
#define		ID_STR_DLG_UPLOAD_SETALLCFG			25002	//正在从设备上传参数数据，请等待......
#define		ID_STR_DLG_UPLOAD_UPLOADING			25003	//正在设备上传数据，请等待......
#define		ID_STR_DLG_UPLOAD_FAILED			25004	//上传数据失败！

#define		ID_STR_DLG_VOIP_TITLE				25021	//网络语音
#define		ID_STR_DLG_VOIP_BCAST				25022	//广播
#define		ID_STR_DLG_VOIP_TBACK				25023	//对讲
#define		ID_STR_DLG_VOIP_MONITOR				25024	//监听
#define		ID_STR_DLG_VOIP_TIP_STOP_TBACK		25025	//当前正在对讲中,确定关闭?
#define		ID_STR_DLG_VOIP_TIP_STOP_BCAST		25026	//当前正在广播中,确定关闭?
#define		ID_STR_DLG_VOIP_CONFILCK_TABCK		25027	//对讲与广播,视频声音或者监听冲突,是否关闭当前的对讲?
#define		ID_STR_DLG_VOIP_CONFLICK_BCAST		25028	//广播与对讲冲突,是否关闭当前的广播?
#define		ID_STR_DLG_VOIP_DEV_STOP_CNT		25029	//设备停止通话
#define		ID_STR_DLG_VOIP_DEV_START			25030	//开启
#define		ID_STR_DLG_VOIP_DEV_STOP			25031	//停止
#define		ID_STR_DLG_VOIP_DEV_SELECT			25032	//选择

#define		ID_STR_DLG_MONITOR_SUCCESS			25041	//语音监听成功
#define		ID_STR_DLG_MONITOR_FAILED			25042	//语音监听失败
#define		ID_STR_DLG_MONITOR_MENU_STOP		25043	//停止监听
#define		ID_STR_DLG_MONITOR_LST_DEV			25044   //监听车辆
#define		ID_STR_DLG_MONITOR_LST_POS			25045	//监听位置
#define		ID_STR_DLG_MONITOR_LST_STATUS		25046   //监听状态
#define		ID_STR_DLG_MONITOR_LST_GROUP		25047	//所属分组
#define		ID_STR_DLG_MONITOR_DEV_ISEXIT		25048	//设备已经在监听！不允许重复添加！
#define		ID_STR_DLG_MONITOR_OPEN_ERR			25049	//语音监听打开失败!
#define     ID_STR_DLG_MONITOR_REQUSTING		25050	//请求中......
#define		ID_STR_DLG_MONITRO_MIC_CHANNEL		25051	//麦克

#define		ID_STR_DLG_BCAST_DUE_ERR			26001	//正在进行对讲，无法再进行语音广播操作！
#define		ID_STR_DLG_BCAST_OPEN_ERR			26002	//开启语音广播失败！系统无麦克输入设备，或者麦克已被其它程序占用！
#define		ID_STR_DLG_BCAST_DEV_DUEING			26003	//已经对监控服务器进行语音广播！
#define		ID_STR_DLG_BCAST_GROUP_DUEING		26004	//已经对此组的监控服务器进行语音广播！
#define		ID_STR_DLG_BCAST_ING				26005	//广播中......
#define		ID_STR_DLG_BCAST_BTN_SOUND			26006	//信息
#define		ID_STR_DLG_BCAST_BTN_DEL			26007	//删除
#define		ID_STR_DLG_BCAST_BTN_STOP			26008	//停止
#define		ID_STR_DLG_BCAST_MENU_DEL			26009	//删除广播
#define		ID_STR_DLG_BCAST_MENU_STOP			26010	//停止广播
#define		ID_STR_DLG_BCAST_MENU_EVENT			26011	//显示事件
#define		ID_STR_DLG_BCAST_MENU_CLEAR_EVENT	26012	//清空事件
#define		ID_STR_DLG_BCAST_LIST_DEVICE		26013	//广播车辆
#define		ID_STR_DLG_BCAST_LIST_STATUS		26014	//状态
#define		ID_STR_DLG_BCAST_LIST_GROUP			26015	//所属分组
#define		ID_STR_DLG_BCAST_LIST_SOUND			26016	//声音开关
#define     ID_STR_DLG_BCAST_LIST_NO            26017   //无      
#define     ID_STR_DLG_BCAST_ALARM_STATUS       26018   //报警状态 
#define     ID_STR_DLG_BCAST_DRIVER_NAME        26019   //司机
#define     ID_STR_DLG_BCAST_GPS_TIME           26020   //gps时间

#define		ID_STR_DLG_REC_SEARCH_RECTYPE_NORMAL	27001	//常规录像
#define		ID_STR_DLG_REC_SEARCH_RECTYPE_ALARM		27002	//报警录像
#define		ID_STR_DLG_REC_SEARCH_LOCATION_DEV		27003	//监控服务器
#define		ID_STR_DLG_REC_SEARCH_LOCATION_RSVR		27004	//存储服务器
#define		ID_STR_DLG_REC_SEARCH_RECTYPE_ALL		27005	//所有录像
#define		ID_STR_DLG_REC_SEARCH_LIST_SEARCH		27006	//搜索列表
#define		ID_STR_DLG_REC_SEARCH_LIST_DOWNING		27007	//正在下载
#define		ID_STR_DLG_REC_SEARCH_ST_DEVICE			27008	//监控服务器
#define		ID_STR_DLG_REC_SEARCH_BTN_SEARCH		27009	//搜索
#define		ID_STR_DLG_REC_SEARCH_BTN_DOWNLOAD		27010	//本地下载
#define		ID_STR_DLG_REC_SEARCH_BTN_PLAYBACK		27011	//回放
#define		ID_STR_DLG_REC_SEARCH_BTN_DOWN_CONFIG	27012	//下载设置
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_TIME	27013	//时间
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_TYPE	27014	//类型
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_FILE	27015	//文件
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_CHN	27016	//通道
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_FILE		27017	//文件
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_PROCESS	27018	//下载进度
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_LOCATION	27019	//存储位置
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_REC_LOACATION	27020	//位置
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_DEV		27021	//监控服务器
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_SIZE		27022	//大小
#define		ID_STR_DLG_REC_SEARCH_ED_DEVICE_TIP		27023	//请将监控服务器拖动到此位置
#define		ID_STR_DLG_REC_SEARCH_TIP_SEARCHING		27024	//正在搜索！是否停止搜索，并立即对此监控服务器进行搜索？
#define		ID_STR_DLG_REC_SEARCH_STOP_SEARCHING	27025	//正在搜索！是否停止搜索？
#define		ID_STR_DLG_REC_SEARCH_BTN_STOP_SEARCH	27026	//停止
#define		ID_STR_DLG_REC_SEARCH_TIP_DEV_EMPTY		27027	//请设置进行搜索的监控服务器！设置方法，从监控服务器列表中\r\n将列表拖动到本面板上的监控服务器窗体上。
#define		ID_STR_DLG_REC_SEARCH_LIST_DOWN_OK		27028	//已下载
#define		ID_STR_DLG_REC_SEARCH_TIME_ERROR		27029	//开始时间必须小于结束时间
#define		ID_STR_DLG_REC_SEARCH_ST_TIME			27030	//搜索时间
#define		ID_STR_DLG_REC_SEARCH_ST_TIME_TO		27031	//至
#define		ID_STR_DLG_REC_SEARCH_ST_REC_TYPE		27032	//录像类型
#define		ID_STR_DLG_REC_SEARCH_FAILED			27033	//搜索失败！错误原因：
#define		ID_STR_DLG_REC_SEARCH_DOWNING_ERR		27034	//正在下载录像文件，不支持同时下载多个录像文件！
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_STATUS	27035	//状态
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_ING		27036	//正在下载
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_FAILED	27037	//下载失败
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_SUC		27038	//下载成功
#define		ID_STR_MENU_DFILE_STOP					27039	//停止下载
#define		ID_STR_MENU_DFILE_DELETE				27040	//删除下载
#define		ID_STR_MENU_DFILE_OPEN					27041	//打开文件夹
#define		ID_STR_MENU_DFILE_PLAY					27042	//播放文件
#define		ID_STR_MENU_DFILE_REDOWN				27043	//继续下载
#define		ID_STR_DLG_REC_SEARCH_START_DOWN_FAILED	27044	//下载文件失败
#define		ID_STR_DLG_REC_SEARCH_DOWN_FAILED		27045	//下载文件失败！错误原因：
#define		ID_STR_DLG_REC_SEARCH_DOWN_DELETE		27046	//是否同时删除下载的录像文件？
#define		ID_STR_DLG_REC_SEARCH_DOWN_DELETE_ING	27047	//文件正在下载！请删除后，再执行下载操作
#define		ID_STR_DLG_REC_SEARCH_DOWN_REDOWN		27048	//文件已经下载成功，重新下载将删除文件！是否重新下载？
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_STOP		27049	//停止下载
#define		ID_STR_DLG_REC_SEARCH_DOWN_ED			27050	//文件已经下载成功！
#define		ID_STR_MENU_RECSEARCH_PLAY				27051	//录像回放
#define		ID_STR_MENU_RECSEARCH_DOWN				27052	//本地下载
#define		ID_STR_DLG_REC_SEARCH_PLAY_NO_DOWN_OK	27053	//文件没有下载成功，请下载成功再执行播放操作
#define		ID_STR_DLG_REC_SEARCH_WND_USED			27054	//当前窗口未处于空闲状态，请选择其它窗口选择播放操作！
#define		ID_STR_DLG_RECS_PLAY_TYPE_LOCAL			27055	//本地回放
#define		ID_STR_DLG_RECS_PLAY_TYPE_REMOTE		27056	//远程回放
#define		ID_STR_DLG_RECS_PLAY_NONE				27057	//未进行录像回放
#define		ID_STR_DLG_RECS_PLAY_RUNNING			27058	//本文件已经处于播放状态！
#define		ID_STR_DLG_RECS_DEL_PLAY_RUNNING		27059	//文件正在播放，无法执行删除操作！
#define		ID_STR_MENU_DFILE_PATH					27060	//下载路径设置
#define		ID_STR_DLG_RECS_ST_PLAY					27061	//播放控制
#define		ID_STR_DLG_RECS_ST_DOWN					27062	//搜索及下载
#define		ID_STR_DLG_RECS_ERRCH_LOACTION_DISK		27063	//本地磁盘
#define     ID_STR_DLG_RECS_ST_FILE_TYPE			27064	//文件类型
#define		ID_STR_DLG_RECS_CMB_FILE_TYPE_JPEG		27065	//图片
#define		ID_STR_DLG_RECS_CMB_FILE_TYPE_RECORD	27066	//录像
#define		ID_STR_DLG_RECS_ST_JPEG_TYPE			27067	//图片类型
#define		ID_STR_DLG_RECS_BTN_PIC_PREVIEW			27068	//预览图片
#define		ID_STR_DLG_RECS_LIST_DOWN_TIP			27069	//下载提示
#define		ID_STR_DLG_RECS_LIST_DOWN_EXIST			27070	//已经存在下载列表中
#define		ID_STR_DLG_RECS_LIST_DOWN_WAITING		27071	//等待中
#define		ID_STR_DLG_RECS_BTN_DOWN_TASK			27072	//远程下载
#define		ID_STR_DLG_RECS_TASK_SUBMIT_SUCCESS		27073	//任务提交成功!
#define		ID_STR_DLG_RECS_TASK_SUBMIT_FAILED		27074	//任务提交失败!
//#define		ID_STR_MENU_RECSEARCH_TASK				27076	//远程下载
#define     ID_STR_DLG_RECS_ERRCH_DOWNLOAD_SER      27075   //下载服务器
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_RATE		27076	//下载速度
#define		ID_STR_DLG_REC_SEARCH_LST_TIP			27077	//双击录像列表打开回放分析软件。
#define		ID_STR_DLG_REC_SEARCH_LOCATION_DOWN_SERVER			27078	//下载服务器
#define		ID_STR_DLG_REC_GPLAYER_UN_INSTll		27079	//您系统未安装回放分析软件, 点击确定进行下载.
#define		ID_STR_DLG_MAPINFO_UN_INSTll			27080	//您系统未安装mapinfo, 点击确定进行下载.
#define		ID_STR_DLG_MAP_CHANGE_REBOOT			27081	//地图改变，系统需要重启.
#define		ID_STR_DLG_REC_ALL_CHANNEL				27082	//所有通道
#define		ID_STR_DLG_REC_SEARCH_RECORD_TIME		27083	//时间
#define		ID_STR_DLG_REC_SEARCH_RECORD_FILE		27084	//文件
#define		ID_STR_DLG_REC_SEARCH_RECORD_DOWN		27085	//下载
	

#define		ID_STR_DLG_PLAY_BTN_PLAY				27101	//播放
#define		ID_STR_DLG_PLAY_BTN_PAUSE				27102	//暂停
#define		ID_STR_DLG_PLAY_BTN_STOP				27103	//停止
#define		ID_STR_DLG_PLAY_BTN_SLOW				27104	//慢放
#define		ID_STR_DLG_PLAY_BTN_FAST				27105	//快进
#define		ID_STR_DLG_PLAY_BTN_STEP				27106	//I帧播放
#define		ID_STR_DLG_PLAY_TIP_PREVIEW				27107	//请切换到预览窗口，再进行操作！
#define		ID_STR_SEARCH_PLAY						27108	//搜索及回放
#define		ID_STR_POSITION							27109	//位置
#define		ID_STR_DLG_PLAY_BTN_STOP_STEP			27110	//停止I帧
#define		ID_STR_PLAYBACK_TIP						27111	//温馨提示:远程回放录像文件较大,回放会出现停顿.

#define		ID_STR_DLG_ARMSETUP_TITLE			30001	//报警联动配置
#define		ID_STR_DLG_ARMSETUP_ST_TYPE			30002	//报警类型
#define		ID_STR_DLG_ARMSETUP_ST_ACTION		30003	//报警联动
#define		ID_STR_DLG_ARMSETUP_ST_TIME			30004	//布防设置
#define		ID_STR_DLG_ARMSETUP_CHK_TIME		30005	//启用
#define		ID_STR_DLG_ARMSETUP_ST_TO			30006	//至
#define		ID_STR_DLG_ARMSETUP_CHK_CENTERMAP	30007	//居中地图
#define		ID_STR_DLG_ARMSETUP_CHK_SHOWTIP		30008	//信息提示
#define		ID_STR_DLG_ARMSETUP_ST_A_COUNT		30009	//播放次数
#define		ID_STR_DLG_ARMSETUP_ST_A_WAV		30010	//声音文件
#define		ID_STR_DLG_ARMSETUP_ST_V_CHN		30011	//预览通道
#define		ID_STR_DLG_ARMSETUP_CHK_VIDEO		30012	//视频预览
#define		ID_STR_DLG_ARMSETUP_CHK_AUDIO		30013	//声音报警
#define		ID_STR_DLG_ARMSETUP_RADIO_IO1		30014	//IO1输入报警
#define		ID_STR_DLG_ARMSETUP_RADIO_IO2		30015	//I02输入报警
#define		ID_STR_DLG_ARMSETUP_RADIO_IA		30016	//智能分析报警
#define		ID_STR_DLG_ARMSETUP_RADIO_DEGREE	30017	//温度报警
#define		ID_STR_DLG_ARMSETUP_RADIO_NET		30018	//断线报警
#define		ID_STR_DLG_ARMSETUP_RADIO_OTHER		30019	//其它报警
#define		ID_STR_DLG_ARMSETUP_CHANGE_SAVE		30020	//报警联动配置信息已经发生改变，是否保存？
#define		ID_STR_DLG_ARMSETUP_A_COUNT_ERR		30021	//声音播放次数范围在1-10之间，请重新输入！
#define		ID_STR_DLG_ARMSETUP_BTN_SAVE		30022	//保存
#define		ID_STR_DLG_ARMSETUP_BTN_APPLy		30023	//保存到多个车辆
#define		ID_STR_DLG_ARMSETUP_BTN_PLAY		30024	//试听
#define		ID_STR_DLG_ARMSETUP_ST_A_RANGE		30025	//(1-10)
#define		ID_STR_DLG_ARMSETUP_TIME_ERR		30026	//布防的开始时间必须小于结束时间！请重新输入！
#define		ID_STR_DLG_ARMSETUP_ST_V_STREAM		30027	//码流类型
#define     ID_STR_DLG_ARMSETUP_BTN_SETDEF		30028	//设置为默认配置	
#define     ID_STR_DLG_ARMSETUP_BTN_LOADDEF		30029   //加载默认配置
#define     ID_STR_DLG_ARMSETUP_ST_PS			30030	//备注:当该车辆没有配置联动报警时将加载默认配置！
#define     ID_STR_DLG_ARMSETUP_CH_ALERM_VIDEO  30031   //报警联动录像
#define     ID_STR_DLG_ARMSETUP_ALARM_V_COUNT   30032   //录像时间
#define     ID_STR_DLG_ARMSETUP_ALARM_V_COUNT_W 30033   //报警联动录像时间介于%d-%d秒之间!
#define     ID_STR_DLG_ARMSETUP_WAV_TIP         30034   //添加声音报警,点"浏览"将.wav格式文件拷贝到
#define		ID_STR_DLG_ARMSETUP_TYPE_SPEED		30035	//速度报警
#define		ID_STR_DLG_ARMSETUP_TYPE_DISK		30036	//硬盘报警
#define		ID_STR_DLG_ARMSETUP_TYPE_VIDEO		30037	//视频报警
#define		ID_STR_DLG_ARMSETUP_TYPE_OTHER		30038	//其它报警
#define		ID_STR_DLG_ARMSETUP_TYPE_OPERATOR	30039	//操作报警
#define		ID_STR_DLG_ARMSETUP_TYPE_EXCEPTION	30040	//故障报警
#define		ID_STR_DLG_ARMSETUP_DISK2_NO_EXIST	30041	//硬盘2不存在
#define		ID_STR_DLG_ARMSETUP_DISK1_NO_EXIST	30042	//硬盘1不存在
#define		ID_STR_DLG_ARMSETUP_SPEED_LOW		30043	//低速报警
#define		ID_STR_DLG_ARMSETUP_SPEED_HIGH		30044	//高速报警
#define		ID_STR_DLG_ARMSETUP_TYPE_OIL		30045	//油量报警
#define		ID_STR_DLG_ARMSETUP_ADD_OIL			30046	//加油报警
#define		ID_STR_DLG_ARMSETUP_DEC_OIL			30047	//油量减少报警

#define		ID_STR_TYPE_UNKNOW					31001	//未知
#define		ID_STR_ALARM_TYPE_USEDEFINE			31003	//自定义报警
#define		ID_STR_ALARM_TYPE_URGENCY_BUTTON	31004	//紧急按钮报警
#define		ID_STR_ALARM_TYPE_SHAKE				31005	//振动报警
#define		ID_STR_ALARM_TYPE_VIDEO_LOST		31006	//视频无信号
#define		ID_STR_ALARM_TYPE_VIDEO_MASK		31007	//视频遮挡
#define		ID_STR_ALARM_TYPE_DOOR_OPEN_LAWLESS	31008	//非法开门报警
#define		ID_STR_ALARM_TYPE_WRONG_PWD			31009	//三次密码错误报警
#define		ID_STR_ALARM_TYPE_FIRE_LOWLESS		31010	//非法点火报警
#define		ID_STR_ALARM_TYPE_TEMPERATOR		31011	//温度报警
#define		ID_STR_ALARM_TYPE_DISK_ERROR		31012	//硬盘错误报警
#define		ID_STR_ALARM_TYPE_OVERSPEED			31013	//超速/低速报警
#define		ID_STR_ALARM_TYPE_BEYOND_BOUNDS		31014	//越界报警
#define		ID_STR_ALARM_TYPE_DOOR_ABNORMAL		31015	//异常开关车门
#define		ID_STR_ALARM_TYPE_DEV_ONLINE		31016	//设备通信恢复
#define		ID_STR_ALARM_TYPE_DEV_DISONLINE		31017	//设备通信中断
#define		ID_STR_ALARM_CONFIRM				31018	//取消报警状态
#define		ID_STR_ALARM_START					31019	//报警开始
#define		ID_STR_ALARM_END					31020	//报警结束
#define     ID_STR_ALARM_TYPE_ACC_ON            31021   //ACC开启报警
#define     ID_STR_ALARM_TYPE_ACC_OFF           31022   //ACC关闭报警
#define     ID_STR_ALARM_TYPE_PARK_TOO_LONG     31023   //停车时间过长报警
#define     ID_STR_ALARM_TYPE_MOTION_DETECT     31024   //移动侦测报警
#define     ID_STR_ALARM_TYPE_GPS_SIGNAL_LOSS   31025   //GPS讯号丢失报警
#define     ID_STR_ALARM_TYPE_LOW_SPEED         31026   //低速报警 
#define     ID_STR_ALARM_TYPE_FENCE_IN		    31027   //进入电子围栏报警 
#define     ID_STR_ALARM_TYPE_FENCE_OUT		    31028   //出电子围栏报警 
#define     ID_STR_ALARM_TYPE_FENCE_IN_OVER_SPEED		    31029   //电子围栏内超速报警 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_OVER_SPEED		    31030   //电子围栏外超速报警 
#define     ID_STR_ALARM_TYPE_FENCE_IN_LOWE_SPEED		    31031   //电子围栏内低速报警 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_LOWE_SPEED		    31032   //电子围栏外低速报警 
#define     ID_STR_ALARM_TYPE_FENCE_IN_STOP				    31033   //电子围栏内停车报警 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_STOP				31034   //电子围栏外停车报警
#define     ID_STR_ALARM_TYPE_IN_FENCE		    31035   //电子围栏内 
#define     ID_STR_ALARM_TYPE_OUT_FENCE		    31036   //电子围栏外 
#define     ID_STR_ALARM_TYPE_FIRE		    31037   //火警
#define     ID_STR_ALARM_TYPE_PANIC		    31038   //劫警
#define     ID_STR_ALARM_TYPE_TASK_FINISHED		    31039   //调度任务完成
#define     ID_STR_ALARM_TYPE_IMAGE_UPLOAD		    31040   //图片上传完成
#define		ID_STR_ALARM_TYPE_FLOW_DAY_REMIND		31041	//日流量预警
#define		ID_STR_ALARM_TYPE_FLOW_DAY_OVER			31042	//日流量超过
#define		ID_STR_ALARM_TYPE_FLOW_MONTH_REMIND		31043	//月流量预警
#define		ID_STR_ALARM_TYPE_FLOW_MONTH_OVER		31044	//月流量超过
#define		ID_STR_ALARM_TYPE_POWER_DOWN			31045	//电池供电
#define		ID_STR_ALARM_TYPE_DOOR_OPEN				31046	//车门开
#define		ID_STR_ALARM_TYPE_ZONE_OPEN				31047	//车辆设防
#define		ID_STR_ALARM_TYPE_LOW_BATTERY_VOLTAGE	31048	//电池电压过低
#define		ID_STR_ALARM_TYPE_BATTERY_BAD			31049	//电池坏
#define		ID_STR_ALARM_TYPE_ENGINE_BAD			31050	//发动机故障

#define		ID_STR_EVENT_INFO_SVR_DISCNT		31051	//中心服务器连接中断，客户端服务受限制
#define		ID_STR_EVENT_INFO_SVR_RECNT			31052	//成功登录中心服务器
#define		ID_STR_EVENT_INFO_ARMSVR_DISCNT		31053	//报警服务器连接中断，将无法接收报警信息
#define		ID_STR_EVENT_INFO_ARMSVR_RECNT		31054	//成功连接报警服务器
#define		ID_STR_EVENT_INFO_USR_CHANGE		31055	//用户信息发生变化，登录服务器失败！
#define		ID_STR_EVENT_INFO_LOAD_FAILED		31056	//重新加载信息失败！请重新登录服务器！
#define		ID_STR_EVENT_INFO_OPEN_SOUND		31057	//创建声音播放对象失败，将无法播放报警声音！
#define		ID_STR_EVENT_INFO_CONFIRM_ALARM		31058	//取消设备[%s]报警状态
#define		ID_STR_EVENT_INFO_PTZ_FAILED		31059	//云台控制失败！错误原因：

#define		ID_STR_EVENT_TYPE_SVR_DISCNT		31061	//服务器连接中断
#define		ID_STR_EVENT_TYPE_SVR_RECNT			31062	//服务器通信恢复
#define		ID_STR_EVENT_TYPE_ALARM_CHN			31063	//镜头：
#define		ID_STR_EVENT_TYPE_FLASH_DEV			31064	//设备信息更新
#define		ID_STR_EVENT_TYPE_UNKNOW			31065	//未报警
#define		ID_STR_EVENT_TYPE_INFO				31066	//提示信息
#define		ID_STR_EVENT_TYPE_OVERSPEED			31067	//超速报警
#define		ID_STR_EVENT_TYPE_REFUEL			31068	//加油
#define		ID_STR_EVENT_TYPE_STILL_FUEL		31069	//油量减少
#define		ID_STR_EVENT_TYPE_ALARM_OIL_BEGIN	31070	//报警前油量
#define		ID_STR_EVENT_TYPE_ALARM_OIL_END		31071	//报警油后油量


#define		ID_STR_DESC_USEDEFINE				31101	//报警编号: %d，报警源: %s，报警名称: %s
#define		ID_STR_DESC_URGENCY_BUTTON			31102	//按钮编号: %d，别名: %s
#define		ID_STR_DESC_SHAKE					31103	//
#define		ID_STR_DESC_DOOR_FORNT				31104	//前门
#define		ID_STR_DESC_DOOR_MIDDLE				31105	//中门
#define		ID_STR_DESC_DOOR_BACK				31106	//后门
#define		ID_STR_DESC_TEMP_LOWEST				31107	//最低温度
#define		ID_STR_DESC_TEMP_HIGHTEST			31108	//最高温度
#define		ID_STR_DESC_DISK_ERROR				31109	//硬盘号: %d，错误描述: %s
#define		ID_STR_DESC_SPEED_ALARM				31110	//报警速度
#define		ID_STR_DESC_SPEED_LOWEST			31111	//最低速度
#define		ID_STR_DESC_SPEED_HIGHTEST			31112	//最高速度
#define		ID_STR_DESC_SPEED_TIME				31113	//持续时间
#define		ID_STR_DESC_BEYOND_BOUNDS_INT		31114	//驶入报警
#define		ID_STR_DESC_BEYOND_BOUNDS_OUT		31115	//驶出报警
#define		ID_STR_DESC_BEYOND_BOUNDS_NO		31116	//围栏号
#define		ID_STR_DESC_DOOR_ABNORMAL_1			31117	//车到站未停开车门
#define		ID_STR_DESC_DOOR_ABNORMAL_2			31118	//车离站行走未关车门
#define		ID_STR_DESC_DOOR_ABNORMAL_3			31119	//车未到站开车门
#define     ID_STR_DESC_REAL_TEMP               31120   //实时温度



#define		ID_STR_DLG_RELOGIN_TITLE			32001	//目录服务器通信中断
#define		ID_STR_DLG_RELOGIN_ST_TIP			32002	//正在重新登录请等待
#define		ID_STR_DLG_RELOGIN_CANCEL			32003	//退出系统
#define		ID_STR_DLG_RELOGIN_BTN_CHANGE		32004	//切换用户

#define		ID_STR_MENU_SYS						33001	//系统
#define		ID_STR_MENU_SYS_EXIT				33002	//系统退出
#define		ID_STR_MENU_VIEW					33003	//视图
#define		ID_STR_MENU_MGR						33008	//管理
#define		ID_STR_MENU_MGR_USR					33009	//用户管理
#define		ID_STR_MENU_MGR_DEV					33010	//设备管理
#define		ID_STR_MENU_MGR_MSVR				33011	//流媒体服务器管理
#define		ID_STR_MENU_MGR_MSVR_TRAN			33012	//转发配置管理
#define		ID_STR_MENU_MGR_RECSVR				33013	//录像服务器管理
#define		ID_STR_MENU_MGR_REC_POS				33014	//录像存储配置
#define		ID_STR_MENU_MGR_ARMSVR				33015	//报警服务器管理
#define		ID_STR_MENU_MGR_PREVIEW				33016	//预览管理
#define		ID_STR_MENU_MGR_RECPLAN				33017	//录像计划管理
#define		ID_STR_MENU_MGR_ARMACTION			33018	//报警联动配置
#define		ID_STR_MENU_HELP					33019	//帮助
#define		ID_STR_MENU_HELP_ABOUT				33020	//关于
#define		ID_STR_MENU_LOG_ALARM				33021	//报警日志查询
#define		ID_STR_MENU_LOG_USR					33022	//用户日志查询
#define		ID_STR_MENU_TOOL					33023	//工具
#define		ID_STR_MENU_BAR						33024	//菜单栏
#define		ID_STR_PANE_BAR						33025	//标准工具栏
#define		ID_STR_VIEW_BAR						33026	//视频窗口工具栏
#define		ID_STR_FULL_BAR						33027	//全屏
#define		ID_STR_SKIN_BAR						33028	//外观
#define		ID_STR_MENU_FULLSCREEN				33029	//全屏
#define		ID_STR_MENU_VOLUME					33030	//音量
#define		ID_STR_MENU_SNAP_DEV				33031	//前端抓拍
#define		ID_STR_MENU_MGR_SYSTEM				33032	//系统配置
#define		ID_STR_MENU_ALARM					33033	//未确认报警
#define		ID_STR_OTHER_BAR					33034	//其它
#define     ID_STR_MENU_VIDEO_RECORD			33035	//录像设置
#define     ID_STR_MENU_MOD_PWD_CUSS            33036   //修改密码成功
#define     ID_STR_MENU_OLD_PWD     			33037	//输入旧密码有误
#define     ID_STR_MENU_MOD_PWD_OK              33038   //两次输入的新密码不一致，请重新输入!
#define     ID_STR_OLD_PWD                      33039   //旧密码
#define     ID_STR_NEW_PWD                      33040   //新密码
#define     ID_STR_NEW_PWD_OK                   33041   //输入确认密码
#define     ID_STR_TIP_FOR                      33042   //修改密码
#define     ID_STR_NEW_PWD_EMPTY_WARN           33043   //新密码不能为空，请输入新密码!
#define     ID_STR_NEW_OK_PWD_EMPTY_WARN        33044   //确认新密码不能为空，请输入确认新密码!
#define     ID_STR_OLD_PWD_EMPTY_WARN           33045   //旧密码不能为空，请输入旧密码!
#define     ID_STR_OLD_PWD_LEN_WARN             33046   //旧密码密码长度为%d~%d位!
#define     ID_STR_NEW_PWD_LEN_WARN             33047   //新密码长度为%d~%d位!
#define     ID_STR_OK_NEW_PWD_LEN_WARN          33048   //确认密码长度为%d~%d位!
#define     ID_STR_LEN_TIP                      33049   //(4~16位)
#define		ID_STR_NOT_MODIFY_PSW				33050	//当前为测试用户,不能修改密码.

#define		ID_STR_PROMPT_MENU_SYS_EXIT			33051	//退出CMS客户端软件\n退出
#define		ID_STR_PROMPT_MENU_NAVIGATE			33052	//显示车辆、对讲、镜头控制面板\n导航
#define		ID_STR_PROMPT_MENU_PANE_PLAY		33053	//显示录像搜索、下载、回放面板\n搜索
#define		ID_STR_PROMPT_MENU_VIEW_MAP			33054	//同时显示地图及视频界面布局\n地图及视频界面布局
#define		ID_STR_PROMPT_MENU_PANE_MAP			33055	//单独显示地图界面布局\n地图界面布局
#define		ID_STR_PROMPT_MENU_PANE_VIEW		33056	//单独显示视频界面布局\n视频界面布局
#define		ID_STR_PROMPT_MENU_VIEW_POP			33057	//弹出方式显示视频界面\n弹出视频界面
#define		ID_STR_PROMPT_MENU_EVENT			33058	//显示或者隐藏事件面板\n事件面板
#define		ID_STR_PROMPT_MENU_MGR_PREVIEW		33059	//视频窗口轮询设置\n轮询设置
#define		ID_STR_PROMPT_MENU_MGR_ARMACTION	33060	//车辆报警联动配置\n报警联动设置
#define		ID_STR_PROMPT_MENU_LOG_ALARM		33061	//查询车辆历史报警事件\n报警日志查询
#define		ID_STR_PROMPT_MENU_LOG_USR			33062	//查询用户历史操作日志\n用户日志查询
#define		ID_STR_PROMPT_MENU_ABOUT			33063	//显示软件信息及版本\n关于Cms Client
#define		ID_STR_PROMPT_MENU_FULLSCREEN		33064	//全屏显示
#define		ID_STR_PROMPT_MENU_SKIN				33065	//选择框架皮肤
#define		ID_STR_PROMPT_MENU_SKIN_VISTA_BLUE	33066	//Vista Blue
#define		ID_STR_PROMPT_MENU_SKIN_VISTA_BLACK	33067	//Vista Black
#define		ID_STR_PROMPT_MENU_SKIN_SYSTEM		33068	//System
#define		ID_STR_PROMPT_MENU_VIEW_UP			33069	//向上移动视频窗口
#define		ID_STR_PROMPT_MENU_VIEW_DOWN		33070	//向下移动视频窗口
#define		ID_STR_PROMPT_MENU_VIEW_1			33071	//1画面显示视频窗口
#define		ID_STR_PROMPT_MENU_VIEW_4			33072	//4画面显示视频窗口
#define		ID_STR_PROMPT_MENU_VIEW_9			33073	//9画面显示视频窗口
#define		ID_STR_PROMPT_MENU_VIEW_16			33074	//16画面显示视频窗口
#define		ID_STR_PROMPT_MENU_OPEN_SOUND		33075	//打开焦点视频画面的声音
#define		ID_STR_PROMPT_MENU_CLOSE_SOUND		33076	//关闭声音
#define		ID_STR_PROMPT_MENU_OPEN_DUE			33077	//与焦点视频画面的设备进行语音对讲
#define		ID_STR_PROMPT_MENU_CLOSE_DUE		33078	//停止焦点视频画面的语音对讲
#define		ID_STR_PROMPT_MENU_VOLUME			33079	//调整音量大小
#define		ID_STR_PROMPT_MENU_SNAP_DEV			33080	//实时从设备前端抓拍图片
#define		ID_STR_PROMPT_MENU_MGR_SYSTEM		33081	//客户端系统参数配置
#define		ID_STR_PROMPT_MENU_ALARM			33082	//查询未确认的报警信息
#define		ID_STR_PROMPT_MENU_LAYOUT_1			33083	//界面布局1
#define		ID_STR_PROMPT_MENU_LAYOUT_2			33084	//界面布局2
#define		ID_STR_PROMPT_MENU_LAYOUT_3			33085	//界面布局3
#define		ID_STR_PROMPT_MENU_LAYOUT_4			33086	//界面布局4
#define		ID_STR_PROMPT_MENU_LAYOUT_5			33087	//界面布局5
#define		ID_STR_PROMPT_MENU_LAYOUT_6			33088	//界面布局6
#define		ID_STR_PROMPT_MENU_LAYOUT_7			33089	//界面布局7
#define		ID_STR_PROMPT_MENU_LAYOUT_8			33090	//界面布局8
#define		ID_STR_LAYOUT_1						33091	//显示界面布局1
#define		ID_STR_LAYOUT_2						33092	//显示界面布局2
#define		ID_STR_LAYOUT_3						33093	//显示界面布局3
#define		ID_STR_LAYOUT_4						33094	//显示界面布局4
#define		ID_STR_LAYOUT_5						33095	//显示界面布局5
#define		ID_STR_LAYOUT_6						33096	//显示界面布局6
#define		ID_STR_LAYOUT_7						33097	//显示界面布局7
#define		ID_STR_LAYOUT_8						33098	//显示界面布局8
#define		ID_STR_PROMPT_MENU_MAP_VIEW			33099	//地图/视频
#define		ID_STR_TOOLTIP_NAVIGATE				33100	//显示车辆列表面板
#define		ID_STR_TOOLTIP_PLAY					33101	//显示录像搜索及下载面板
#define		ID_STR_CAM_PTZ						33102	//云台
#define		ID_STR_CAM_COLOR					33103	//颜色
#define		ID_STR_PROMPT_MENU_AV_START			33104	//启动视频
#define		ID_STR_PROMPT_MENU_AV_STOP			33105	//停止视频
#define		ID_STR_PROMPT_MENU_AV_START_ALL		33106	//开启所有视频
#define		ID_STR_PROMPT_MENU_AV_STOP_ALL		33107	//停止所有视频
#define		ID_STR_PROMPT_MENU_AV_CLEAR			33108	//清除数据
#define		ID_STR_PROMPT_MENU_AV_CLEAR_ALL		33109	//清除所有数据
#define		ID_STR_PROMPT_MENU_PANE_TRACK		33110	//显示轨迹搜索、回放面板\n轨迹
#define		ID_STR_TOOLTIP_TRACK				33111	//显示估计搜索及回放面板
#define		ID_STR_PROMPT_MENU_MGR_VIDEOREC		33112	//客户端录像参数配置
#define		ID_STR_PROMPT_MENU_OPEN_CMDSEND		33113	//短消息

#define		ID_STR_DLG_ARMTIP_TITLE				34001	//报警提示
#define		ID_STR_DLG_ARMTIP_ST_DEV			34002	//监控服务器
#define		ID_STR_DLG_ARMTIP_ST_TYPE			34003	//报警类型
#define		ID_STR_DLG_ARMTIP_ST_TIME			34004	//报警时间
#define		ID_STR_DLG_ARMTIP_ST_DESC			34005	//报警描述
#define		ID_STR_DLG_ARMTIP_BTN_MORE			34006	//更多
#define		ID_STR_DLG_ARMTIP_BTN_PREV			34007	//上一条
#define		ID_STR_DLG_ARMTIP_BTN_NEXT			34008	//下一条
#define		ID_STR_DLG_ARMTIP_BTN_MAP			34009	//地图显示
#define		ID_STR_DLG_ARMTIP_ST_DEALPLAN		34010   //处警方案
#define		ID_STR_DLG_ARMTIP_ST_DEALALARM		34011   //报警处理
#define		ID_STR_DLG_ARMTIP_BTN_DEALALARM		34012   //报警处理
#define		ID_STR_DLG_ARMTIP_DEALALARM_TIP		34013	//处理内容不能大于128个字符，请确认！
#define     ID_STR_DLG_ARMTIP_ALARM_DEAL_STA	34014	//报警处理状态
#define     ID_STR_DLG_ARMTIP_ALARM_NOCONFIRM	34015	//报警未处理
#define     ID_STR_DLG_ARMTIP_ALARM_CONFIRMED	34016	//报警已经处理
#define		ID_STR_DLG_ARMTIP_ALARM_NONEED		34017	//无需处理		
#define		ID_STR_DLG_ARMTIP_ALARM_TREATMENT	34018	//处理方法
#define		ID_STR_DLG_ARMTIP_ALARM_TREATTIME	34019	//处理时间
#define		ID_STR_DLG_ARMTIP_ALARM_TREATUSER	34020	//处理用户
#define		ID_STR_DLG_ARMTIP_ALARM_LANGANDLAT	34021	//经纬度
#define		ID_STR_DLG_ARMTIP_TITLE_ALL			34022	//未处理报警
#define     ID_STR_DLG_ARMTIP_ST_SELECT_VEH		34023	//选择车辆
#define		ID_STR_DLG_ARMTIP_ST_HANDLING_STA	34024	//处理状态
#define		ID_STR_DLG_ARMTIP_TITLE_ARM_LOG		34025	//报警日志处理
#define		ID_STR_DLG_ARMTI_HANDLE_FAILED		34026   //处理失败
#define		ID_STR_DLG_ARMTI_DEV_CONTROL		34027   //车辆控制

#define		ID_STR_DLG_LOG_QUERY_TITLE			35001	//日志查询
#define		ID_STR_DLG_LOG_ALARM_TITLE			35002	//报警日志查询
#define		ID_STR_DLG_LOG_USR_TITLE			35003	//用户日志查询
#define		ID_STR_DLG_LOG_ARM_ST_TYPE			35004	//报警类型
#define		ID_STR_DLG_LOG_ARM_ST_TIME_BEG		35005	//开始时间
#define		ID_STR_DLG_LOG_ARM_ST_TIME_END		35006	//结束时间
#define		ID_STR_DLG_LOG_ARM_BTN_QUERY		35007	//查询
#define		ID_STR_DLG_LOG_ARM_ALL				35008	//所有报警
#define		ID_STR_DLG_LOG_ARM_TIME_ERR			35009	//搜索开始时间必须小于结束时间，请重新输入！
#define		ID_STR_DLG_LOG_ARM_DEV_ERR			35010	//请选择查询的设备！
#define		ID_STR_DLG_LOG_QUERY_FAILED			35011	//查询失败！错误原因：
#define		ID_STR_DLG_LOG_ARM_CONFIRM_TYPE		35012   //手动确认报警类型
#define		ID_STR_DLG_LOG_ARM_AFFIRM_ALL		35013	//手动确认全部
#define		ID_STR_DLG_LOG_ARM_AFFIRM_NO		35014   //没有手动确认的
#define		ID_STR_DLG_LOG_ARM_AFFIRM_OK		35015	//已经手动确认的报警
#define		ID_STR_DLG_LOG_ARM_BTN_EXPROT		35016   //导出Exsle表
#define		ID_STR_DLG_LOG_EXCEL_TABLE_NM		35017	//Exsetl表名称
#define		ID_STR_DLG_LOG_ARM_TIP_TITEL		35018   //提示:
#define		ID_STR_DLG_LOG_ARM_TIP_TEXT			35019	//黑色-无需处理,红色-需处理，蓝色-已处理
#define		ID_STR_DLG_LOG_BTN_STOP_QUERY		35020   //停止查询
#define		ID_STR_DLG_LOG_SHOW_PAGE      		35021	//每页显示%d,当前为%d页
#define		ID_STR_DLG_LOG_WAITE_FOR     		35022   //正在获取用户信息，请等待......
#define		ID_STR_DLG_LOG_INFO_FAIL_GET		35023	//获取用户信息失败
#define		ID_STR_DLG_LOG_INFO_SUCC_GET		35024   //获取用户信息成功

#define		ID_STR_EXCEL_EXPT_FILEDLG_TITLE		35051	//导出Excel表	
#define		ID_STR_EXCEL_EXPT_TIP_NODIRVER		35052	//没有安装Excel!\n请先安装Excel软件才能使用导出功能!
#define		ID_STR_EXCEL_EXPT_TIP_SUCCEED		35053	//导出文件保存于
#define		ID_STR_EXCEL_EXPT_TIP_OV_FAILED		35054	//覆盖文件时出错！
#define     ID_STR_EXCEL_EXPT_FILTER			35055   //Excel文件(*.xls)

#define		ID_STR_DLG_LOG_USR_ST_LOG			35101	//系统用户
#define		ID_STR_DLG_LOG_USR_LST_USR			35102	//用户
#define		ID_STR_DLG_LOG_USR_ALL_USR			35103	//所有用户
#define		ID_STR_USER_NO_PRIVILEGE			35104	//当前用户无此权限

#define		ID_STR_LOG_TYPE_LOGIN				35201	//用户登录
#define		ID_STR_LOG_TYPE_MGR_DEV				35202	//设备管理
#define		ID_STR_LOG_TYPE_MGR_USR				35203	//用户管理
#define		ID_STR_LOG_TYPE_MGR_MAP				35204	//地图管理
#define		ID_STR_LOG_TYPE_MEIDA_SVR			35205	//流媒体服务器管理
#define		ID_STR_LOG_TYPE_RECORD_SVR			35206	//录像服务器管理
#define		ID_STR_LOG_TYPE_REC_PLAN			35207	//录像计划管理
#define		ID_STR_LOG_TYPE_MDEV_TRAN			35208	//流媒体转发配置
#define		ID_STR_LOG_TYPE_REC_POS				35209	//设备存储配置
#define		ID_STR_LOG_TYPE_ALARM_SVR			35210	//报警服务器管理
#define		ID_STR_LOG_TYPE_MATRIX				35211	//电视墙管理
#define		ID_STR_LOG_TYPE_UNKNOW				35212	//未知

#define		ID_STR_DLG_ARM_LAST_TITLE			36001	//查看未确认报警
#define		ID_STR_DLG_ARM_LAST_BTN_QUERY		36002	//查询更多报警
#define		ID_STR_DLG_ARM_LAST_BTN_CONFRIM		36003	//确认报警
#define		ID_STR_DLG_ARM_LAST_ST_DEV			36004	//选择车辆
#define		ID_STR_DLG_ARM_LAST_BTN_REFRESH		36005	//刷新报警

#define		ID_STR_PTZ_ZOOM_ADD					37001	//焦点前调
#define		ID_STR_PTZ_ZOOM_DEL					37002	//焦点后调
#define		ID_STR_PTZ_FOCUS_ADD				37003	//焦距变大
#define		ID_STR_PTZ_FOCUS_DEL				37004	//焦距变小
#define		ID_STR_PTZ_LIGHT_ADD				37005	//光圈放大
#define		ID_STR_PTZ_LIGHT_DEL				37006	//光圈缩小
#define		ID_STR_PTZ_LIGHT_ON					37007	//打开灯光
#define		ID_STR_PTZ_LIGHT_OFF				37008	//关闭灯光
#define		ID_STR_PTZ_WIPER_ON					37009	//打开雨刷
#define		ID_STR_PTZ_WIPER_OFF				37010	//关闭雨刷
#define		ID_STR_PTZ_PRESET_NEXT				37011	//上一页
#define		ID_STR_PTZ_PRESET_PREV				37012	//下一页
#define		ID_STR_PTZ_TOP						37013	//上
#define		ID_STR_PTZ_LEFT_TOP					37014	//左上
#define		ID_STR_PTZ_RIGHT_TOP				37015	//右上
#define		ID_STR_PTZ_LEFT						37016	//左
#define		ID_STR_PTZ_RIGHT					37017	//右
#define		ID_STR_PTZ_LEFT_BOTTOM				37018	//左下
#define		ID_STR_PTZ_RIGHT_BOTTOM				37019	//右下
#define		ID_STR_PTZ_BOTTOM					37020	//下
#define		ID_STR_PTZ_AUTO_CRUISE				37021	//自动巡航
#define		ID_STR_PTZ_PRESET_MOVE				37022	//调用
#define		ID_STR_PTZ_PRESET_SET				37023	//设置
#define		ID_STR_PTZ_PRESET_DEL				37024	//删除
#define		ID_STR_PTZ_TIP_PRESET_MOVE			37025	//调用预置点
#define		ID_STR_PTZ_TIP_PRESET_SET			37026	//设置预置点
#define		ID_STR_PTZ_TIP_PRESET_DEL			37027	//删除预置点
#define		ID_STR_PTZ_ZOOM						37028	//变倍
#define		ID_STR_PTZ_FOCUS					37029	//焦距
#define		ID_STR_PTZ_LIGHT					37030	//光圈
#define		ID_STR_PTZ_NO_PREVIEW_TIP			37031	//请选中实时预览窗口后，再执行云台操作！


#define		ID_STR_COLOR_BRI					38001	//亮度
#define		ID_STR_COLOR_CON					38002	//对比度
#define		ID_STR_COLOR_HUE					38003	//色调
#define		ID_STR_COLOR_SAT					38004	//饱合度
#define		ID_STR_COLOR_DEFAULT				38005	//默认

#define		ID_STR_DLG_SYSTEM_TITLE				39001	//系统设置
#define		ID_STR_DLG_SYSTEM_ST_SYS			39002	//系统参数
#define		ID_STR_DLG_SYSTEM_ST_LANG			39003	//系统语言
#define		ID_STR_DLG_SYSTEM_ST_VIEW			39004	//视频参数
#define		ID_STR_DLG_SYSTEM_ST_VIEW_SIZE		39005	//显示比例
#define		ID_STR_DLG_SYSTEM_ST_VIEW_MODE		39006	//显示模式
#define		ID_STR_DLG_SYSTEM_ST_PATH			39007	//路径参数
#define		ID_STR_DLG_SYSTEM_ST_FILE_DOWN		39008	//文件下载
#define		ID_STR_DLG_SYSTEM_ST_PIC_CAPTURE	39009	//图片抓拍
#define		ID_STR_DLG_SYSTEM_BTN_BROWSE		39010	//浏览
#define		ID_STR_DLG_SYSTEM_BTN_SAVE			39011	//保存
#define		ID_STR_DLG_SYSTEM_BTN_TIP_SUC		39012	//保存成功
#define		ID_STR_DLG_SYSTEM_BTN_TIP_REBOOT	39013	//保存成功！语言参数、地图类型或者界面风格改变需要重启生效！
#define		ID_STR_DLG_SYSTEM_VEHI_COUNT_TIP	39014	//地图参数中显示车辆数目参数在%d-%d之间，请重新输入！
#define		ID_STR_DLG_SYSTEM_ST_MAP			39015	//地图参数
#define		ID_STR_DLG_SYSTEM_ST_MAP_TYPE		39016	//地图类型
#define		ID_STR_DLG_SYSTEM_ST_VEHI_COUNT		39017	//地图车辆数目
#define		ID_STR_DLG_SYSTEM_ST_CNT_MODE		39018	//连接模式
#define		ID_STR_DLG_SYSTEM_CHK_MAP_GPSFIX	39019	//GPS校正
#define		ID_STR_DLG_SYSTEM_ST_DELAY_TIME		39020	//视频缓冲时间
#define		ID_STR_DLG_SYSTEM_ST_TIME_UINT		39021	//单位：秒
#define		ID_STR_DLG_SYSTEM_DELAY_TIME_TIP	39022	//视频缓冲时间参数在%d-%d之间，请重新输入！
#define		ID_STR_DLG_SYSTEM_TIME_COMPARE_TIP	39023	//视频缓冲最小时间不得大于最大时间，请重新输入！
#define		ID_STR_DLG_SYSTEM_ST_ARM			39024	//报警参数
#define		ID_STR_DLG_SYSTEM_ST_ARM_COUNT		39025	//未处理报警数目
#define     ID_STR_DLG_SYSTEM_ARM_COUNT_TIP		39026   //报警数目参数在%d-%d之间，请重新输入！
#define		ID_STR_DLG_SYSTEM_ST_DDRAW_RGB16	39027   //Direct Draw 视频
#define		ID_STR_DLG_SYSTEM_CHK_DDRAW_RGB16	39028	//使用RGB16方式
#define		ID_STR_DLG_SYSTEM_LESS_VEHI_TIP		39029	//地图参数中显示车辆数目小于当前地图监控车辆数目，请重新输入！
#define		ID_STR_DLG_SYSTEM_ALARM_SHUT 		39030	//报警视频自动关闭时间参数在%d-%d之间，请重新输入!
#define     ID_STR_DLG_SYSTEM_CK_AUTO_SHUT      39031   //报警视频自动关闭 IDC_CHECK_ALARM_CLOSE  
#define     ID_STR_DLG_SYSTEM_SHUT_TIME         39032   //视频关闭时间
#define     ID_STR_DLG_SYSTEM_KMH               39033   //千米/时
#define     ID_STR_DLG_SYSTEM_MPH               39034   //英里/时
#define     ID_STR_DLG_SYSTEM_SPEED_UNIT        39035   //速度单位
#define     ID_STR_DLG_STSTEM_UNIT_MP           39036   //英里
#define     ID_STR_DLG_STSTEM_UNIT_KM           39037   //千米
#define     ID_STR_DLG_STSTEM_POLLING_WARN      39038   //轮询时间介于%d-%d之间!
#define     ID_STR_DLG_SYSTEM_AUTO_CLOSE_VIDEO  39039   //%分钟后自动关闭视频
#define     ID_STR_DLG_SYSTEM_NOT_CLOSE_VIDEO   39040   //不自动关闭视频
#define     ID_STR_DLG_SYSTEM_SETTING_CLOSE     39041   //关闭视频设置
#define     ID_STR_DLG_SYSTEM_CLOSE_TIP         39042   //客户端无操作的情况下
#define     ID_STR_DLG_SYSTEM_CLOSE_VIEW        39043   //开启视频预览后
#define     ID_STR_DLG_SYSTEM_TRY_TIP           39044   //视频无预览时,可尝试勾选此项!
#define     ID_STR_DLG_SYSTEM_GOOGLE_SPEED      39045   //Google访问加速
#define     ID_STR_DLG_SYSTEM_GOOGLE_SPEED_CK   39046   //是否启动Goole地图访问加速
#define		ID_STR_DLG_SYSTEM_AUTO_CLOSE_VOICE	39047	//关闭对讲和监听
#define		ID_STR_DLG_SYSTEM_CLOSE_VOICE		39048	//打开对讲和监听后
#define     ID_STR_DLG_SYSTEM_UI_STYLE_DEFAULT  39049   //默认(银灰)
#define     ID_STR_DLG_SYSTEM_UI_STYLE_BLUE     39050   //淡蓝
#define     ID_STR_DLG_SYSTEM_UI_STYLE		    39051   //界面风格
#define     ID_STR_DLG_SYSTEM_AUTO_LOGIN		39052   //软件启动自动登录
#define     ID_STR_DLG_SYSTEM_DEFUALT_VIDEO		39053   //默认请求视频


#define		ID_STR_VIEW_MODE_REAL				39501	//实时性好
#define		ID_STR_VIEW_MODE_SMOOTH				39502	//流畅性好
#define		ID_STR_VIEW_SIZE_FULL				39503	//全屏显示
#define		ID_STR_VIEW_SIZE_4_3				39504	//4 : 3
#define		ID_STR_VIEW_SIZE_16_9				39505	//16 : 9
#define		ID_STR_VIEW_MAP_GOOGLE				39506	//Google
#define		ID_STR_VIEW_MAP_MAPINFO				39507	//Mapinfo
#define		ID_STR_VIEW_MODE					39508	//视频模式
#define		ID_STR_VIEW_SIZE					39509	//视频缩放
#define		ID_STR_VIEW_SIZE_PROMPT				39510	//视频画面缩放
#define		ID_STR_VIEW_MODE_CAPTION			39511	//模式
#define		ID_STR_DEV_PROMPT_TRACE				39512	//实时监控车辆状态
#define		ID_STR_DEV_PROMPT_SETUP				39514	//设备参数配置
#define		ID_STR_DEV_SETUP					39515	//车辆参数配置
#define		ID_STR_DEV_TRACE					39516	//实时监控
#define		ID_STR_CNT_MODE_TCP					39517	//Tcp连接
#define		ID_STR_CNT_MODE_UDP					39518	//Udp连接
#define     ID_STR_VIEW_MAP_GOOGLE_CHINA        39519   //Google中国
#define     ID_STR_VIDEO_POLLING_TIME           39520   //轮询时长
#define     ID_STR_VIEW_MAP_BAIDU		        39521   //百度


#define		ID_STR_DLG_GPS_RECORD_TITLE			39550	//轨迹回放历史记录
#define		ID_STR_DLG_GPS_RECORD_DOWM_TIME		39551	//下载时间

#define		ID_STR_DLG_TRACK_TMP				39600	//温度
#define		ID_STR_DLG_TRACK_ST_DEVICE			39601	//车辆设备
#define		ID_STR_DLG_TRACK_BTN_SELECT			39602   //选择车辆
#define		ID_STR_DLG_TRACK_ST_SEARCH_TM		39603   //搜索时间
#define		ID_STR_DLG_TRACK_ST_SEARCH_TMTO		39604	//时间至
#define		ID_STR_DLG_TRACK_BTN_PLAY			39605	//轨迹播放
#define     ID_STR_DLG_TRACK_BTN_PAUSE			39606	//轨迹暂停
#define		ID_STR_DLG_TRACK_BTN_CONTINUE		39607	//轨迹继续
#define		ID_STR_DLG_TRACK_BTN_STOP			39608	//轨迹停止
#define     ID_STR_DLG_TRACK_BTN_DEL			39609	//轨迹删除
#define		ID_STR_DLG_TRACK_ST_TRACK_SPD		39610   //回放速度
#define		ID_STR_DLG_TRACK_ST_SPD_UT			39611   //回放单位
#define		ID_STR_DLG_TRACK_ST_CUR_DEV			39612   //当前车辆
#define		ID_STR_DLG_TRACK_ST_BEG_TIME		39613	//GPS开始时间
#define     ID_STR_DLG_TRACK_ST_END_TIME		39614   //GPS结束时间
#define     ID_STR_DLG_TRACK_ST_CUR_TIME		39615   //GPS当前时间
#define		ID_STR_DLG_TRACK_ST_GPS_LONG		39616	//GPS经度
#define		ID_STR_DLG_TRACK_ST_GPS_LAT			39617	//GPS纬度
#define     ID_STR_DLG_TRACK_ST_DEV_SPD			39618	//车辆速度
#define		ID_STR_DLG_TRACK_ST_DEV_TMP			39619	//车辆温度
#define     ID_STR_DLG_TRACK_ARM_FAIL_REAS		39620	//失败原因
#define		ID_STR_DLG_TRACK_ARM_NO_TRACK		39621	//找到轨迹
#define     ID_STR_DLG_TRACK_ARM_DEL_TRACK		39622	//删除轨迹
#define		ID_STR_DLG_TRACK_BTN_CENTER_VEH		39623   //居中车辆
#define     ID_STR_DLG_TRACK_TIP_TITLE			39624	//提示:
#define		ID_STR_DLG_TRACK_TIP_TEXT			39625	//每%s秒播放一个GPS数据
#define		ID_STR_DLG_TRACK_RESEARCH_TIP		39626   //当前正在播放，确定重新搜索！
#define		ID_STR_DLG_TRACK_SEL_DEV_EMPTY		39627	//请选择一个车辆结点！
#define		ID_STR_DLG_TRACK_TEMPER_SYMBOL		39628	//℃
#define		ID_STR_DLG_TRACK_FAIL       		39629	//失败原因：
#define     ID_STR_DLG_TRACK_PLAY               39630   //轨迹回放
#define     ID_STR_DLG_TRACK_LICHENG            39631   //里程
#define     ID_STR_DLG_TRACK_TIME_WARN          39632   //终止时应该大于起始时间
#define     ID_STR_DLG_TRACK_DAY_COUNT_WARN     39633   //请确保查询的轨迹是最近七天以内的历史轨迹!

#define     ID_STR_DLG_TRACK_PARKING_V          39634   //停车%d秒
#define     ID_STR_DLG_TRACK_NORMAL_FINISH      39635   //正常回放完毕!
#define     ID_STR_DLG_TRACK_CONTRAST_FINISH    39636   //对比回放完毕!             
#define     ID_STR_DLG_TRACK_CONTRAST_WARN      39637   //对比回放最多能回放3次!
#define     ID_STR_DLG_TRACK_NORMAL_AGAIN       39638   //是否要重新搜索正常回放轨迹?
#define     ID_STR_DLG_TRACK_FAST_AGAIN         39639   //是否要重新搜索快速回放轨迹?   
#define     ID_STR_DLG_TRACK_CONTRAST_WARN_TEL  39640   //轨迹对比不能超过3次,是否要重新开始回放?
#define     ID_STR_DLG_TRACK_TYPE               39641   //回放类型
#define     ID_STR_DLG_TRACK_TYPE_SHOW_GPS      39642   //不显示报警事件
#define     ID_STR_DLG_TRACK_TYPE_SHOW_ALAR_GPS 39643   //显示报警事件
#define     ID_STR_DLG_TRACK_TYPE_SHOW_ALARM    39644   //只显示报警事件
#define     ID_STR_DLG_TRACK_DESCRIB            39645   //描述
#define     ID_STR_DLG_TRACK_NORMAL             39646   //正常回放
#define     ID_STR_DLG_TRACK_FAST               39647   //快速回放
#define     ID_STR_DLG_TRACK_CONTRAST           39648   //对比回放
#define     ID_STR_DLG_TRACK_INDEX              39649   //序号
#define     ID_STR_DLG_TRACK_FANGXIANG          39650   //方向

#define		ID_STR_DLG_EXPIRED_TITLE			39651	//过期提示
#define		ID_STR_DLG_EXPIRED_TIP_EXPIRED		39652	//客户端已过期
#define		ID_STR_DLG_EXPIRED_TIP_TIMELEFT		39653   //提示剩余时间%d
#define		ID_STR_DLG_EXPIRED_TBACK_TITLE		39654	//对讲请求
#define		ID_STR_DLG_EXPIRED_TBACK_RQUE		39655	//请求对讲
#define		ID_STR_DLG_EXPIRED_TBACK_ACCEPT		39656	//接受
#define		ID_STR_DLG_EXPIRED_TBACK_REFUSE		39657	//拒绝
#define     ID_STR_DLG_EXPIRED_USE_TITLE		39658	//用户信息提示
#define		ID_STR_DLG_EXPIRED_USER_EXPIRED		39659	//用户已过期！

#define     ID_STR_DLG_TRACK_PROCESS            39660   //  回放进度
#define     ID_STR_DLG_TRACK_PARKING_INTERVAL   39661   //  停车间隔
#define     ID_STR_DLG_TRACK_MINUTE             39662   //  分钟
#define     ID_STR_DLG_TRACK_DIS                39663   //  间距  

#define		ID_STR_DLG_TRACK_DECALITRE			39664	//升decalitre
#define		ID_STR_DLG_TRACK_YOULIANG			39665	//油量
#define		ID_STR_DLG_TRACK_CONTROL			39666	//控制面板
#define		ID_STR_DLG_TRACK_TAG_TRACK			39667	//轨迹
#define		ID_STR_DLG_TRACK_LICHENG_EX			39668	//实时里程/总里程
#define		ID_STR_DLG_TRACK_NO_TRACK_TO_SAVE	39669	//没有轨迹可以保存.


#define		ID_STR_DLG_ABOUT_TITLE				39681	//关于 GPSClient
#define		ID_STR_DLG_ABOUT_ST_VERSION			39682	//GPSClient 1.0 版
#define     ID_STR_DLG_ABOUT_ST_COPYRIGHT		39683	//版权所有 (C) 2010
#define		ID_STR_DLG_ABOUT_ST_EXPIRED			39684   //提示时间

#define     ID_STR_DLG_ARMVIDEO_TITLE			39690	//报警视频

#define		ID_STR_DLG_VIDEOCOVER_TITLE			39701	//预览提示
#define		ID_STR_DLG_VIDEOCOVER_STC_TIP		39702	//是否替换当前预览的焦点窗口?
#define		ID_STR_DLG_VIDEOCOVER_CHK_TIP		39703	//以后不在提示
#define		ID_STR_DLG_VIDEO_MAX_NUM_TIP		39704	//录像的数目不能超过%d
#define     ID_STR_DLG_VIDEO_WARN_START         39705   //车辆%s-通道%d报警录像开始
#define     ID_STR_DLG_VIDEO_WARN_END           39706   //车辆%s-通道%d报警录像结束
#define     ID_STR_DLG_VIDEO_START              39707   //报警录像开始
#define     ID_STR_DLG_VIDEO_RECORDING_TIP      39708   //正在录像,报警录像将录制%d秒
#define     ID_STR_DLG_VIDEO_FINISH             39709   //报警录像结束
#define     ID_STR_DLG_VIDEO_RECORDED_TIME_TIP  39710   //报警录像录制时间%d秒

//#define		ID_STR_DLG_CMDSEND_TITLE			39711	//TTS语音
#define		ID_STR_DLG_CMDSEND_BTN_SEND			39712	//发送
#define		ID_STR_DLG_CMDSEND_BTN_CLOSE		39713	//关闭
#define		ID_STR_DLG_CMDSEND_TEXT_EMPTY		39714	//发送内容不能为空,请重新输入！
#define		ID_STR_DLG_CMDSEND_DEVLIST_EMPTY	39715	//发送车辆列表不能为空,请重新添加！
#define		ID_STR_DLG_CMDSEND_TXTE_OVER		39716	//发送字数不能超过%d字符
#define		ID_STR_DLG_CMDSEND_SEND_FAILD		39717	//发送消息失败
#define		ID_STR_DLG_CMDSEND_SEND_LIST		39718	//发送列表		
#define		ID_STR_DLG_CMDSEND_ST_RECORD_WND	39719	//发送记录
#define		ID_STR_DLG_CMDSEND_ST_SEND_WND		39720	//发送窗口	
#define		ID_STR_DLG_CMDSEND_BAR_DELDEV		39721   //删除
#define		ID_STR_DLG_CMDSEND_BAR_EMPTYDEV		39722	//清空

#define		ID_STR_DLG_DEVUSERINFO_TITLE		39731	//用户信息
#define		ID_STR_DLG_DEVUSERINFO_CHK_SAVE		39732	//是否保存用户信息
#define		ID_STR_DLG_DEVUSERINFO_EMPTY_TIP	39733	//用户名或者密码不能为空
#define		ID_STR_DLG_DEVUSERINFO_MAXNUM_TIP	39734	//用户名或者密码长度不能超过%d个字符
#define     ID_STR_DLG_DEVUSERINFO_WARN_TO      39735   //用户名是由数字和字母组成
#define     ID_STR_DLG_DEVUSERINFO_TELL_TO      39736   //是否将该用户信息运用到其他车辆 IDC_CHK_USE_OTHER

#define		ID_STR_CMD_SEND_FAILED				39741	//发送失败
#define		ID_STR_CMD_SEND_SUCCESS				39742	//发送成功
#define		ID_STR_CMD_ERR_NO_RIGHT				39743	//没有权限

#define		ID_STR_DEV_RECORD_DISK_ERR			39750	//写文件出错，检查磁盘是否已满
#define		ID_STR_DEV_RECORD_DISR_NORMAL		39751   //写文件正常

#define		ID_STR_DLG_PICPREVIEW_TITLE			39761	//预览图片
#define		ID_STR_DLG_PICPREVIEW_BTN_PREV		39762   //前一张
#define		ID_STR_DLG_PICPREVIEW_BTN_NEXT		39763	//下一张
#define		ID_STR_DLG_PICPREVIEW_BTN_BROWSE	39764	//浏览
#define		ID_STR_DLG_PICPREVIEW_ST_GO			39765   //跳转至

#define		ID_STR_DLG_PATHSET_TITLE			39771	//路径选择
#define		ID_STR_DLG_PATHSET_ST_FILE_NAME		39772	//文件名称
#define		ID_STR_DLG_PATHSET_ST_DOWN_PATH		39773	//保存路径
#define		ID_STR_DLG_PATHSET_BTN_BROWSE		39774	//浏览
#define		ID_STR_DLG_PATHSET_BTN_DOWN			39775	//下载	
#define		ID_STR_DLG_PATHSET_SCOURCE_FILENAME	39776	//源文件	

#define		ID_STR_DLG_DEVINFO_TITLE			39781	//车辆信息
#define		ID_STR_DLG_DEVINFO_ST_NAME			39782	//车辆名称
#define		ID_STR_DLG_DEVINFO_ST_ID			39783	//车辆编号
#define		ID_STR_DLG_DEVINFO_ST_NO			39784	//车牌号
#define		ID_STR_DLG_DEVINFO_ST_SIM			39785	//SIM
#define		ID_STR_DLG_DEVINFO_ST_BRAND			39786	//车辆品牌
#define		ID_STR_DLG_DEVINFO_ST_COLOR			39787	//车辆颜色
#define		ID_STR_DLG_DEVINFO_ST_NOTYPE		39788	//车牌类型
#define		ID_STR_DLG_DEVINFO_ST_COMPANY		39789   //公司
#define		ID_STR_DLG_DEVINFO_ST_DRIVER		39790	//司机名称
#define		ID_STR_DLG_DEVINFO_ST_PHONE			39791	//电话
#define		ID_STR_DLG_DEVINFO_ST_NATURE		39792	//车辆性质
#define		ID_STR_DLG_DEVINFO_ST_REMARK		39793	//备注
#define		ID_STR_DLG_DEVINFO_ST_TYPE			39794	//机器类型
#define		ID_STR_DLG_DEVINFO_ST_CHN_NUM		39795	//通道数目
#define		ID_STR_DLG_DEVINFO_ST_IP			39796	//IP
#define		ID_STR_DLG_DEVINFO_ST_CHN_NAME		39797	//通道名称
#define		ID_STR_DLG_DEVINFO_ST_DISK		    39798	//磁盘
#define		ID_STR_DLG_DEVINFO_ST_ALL_CAPACITY	39799	//所有容量
#define		ID_STR_DLG_DEVINFO_ST_SUR_CAPACTTY	39800	//剩余容量
#define		ID_STR_DEV_TYPE_HI3512_SD			39801	//HI3512-Mini-SD
#define		ID_STR_DEV_TYPE_HI3515_DISK			39802	//HI3515-Mini-DISK
#define		ID_STR_DLG_DEVINFO_ST_WAIT_FOR   	39803	//正在获取设备信息，请等待....
#define		ID_STR_DLG_DEVINFO_ST_CP_SUCC		39804	//获取设备信息成功
#define		ID_STR_DLG_DEVINFO_ST_ERR       	39805	//获取设备信息失败！错误原因：
#define		ID_STR_DLG_DEVINFO_BASE          	39806	//车辆基本信息
#define		ID_STR_DLG_DEVINFO              	39807	//设备信息

#define		ID_STR_DLG_DEVINFO_DISK_COUNT		39808	//硬盘数目
#define		ID_STR_DLG_DEVINFO_3G		        39809	//无线模块
#define		ID_STR_DLG_DEVINFO_CK_3G_WIFI       39810	//有效
#define		ID_STR_DLG_DEVINFO_3G_TYPE   		39811	//模块类型
#define		ID_STR_DLG_DEVINFO_NET_IP       	39812	//网络地址
#define		ID_STR_DLG_DEVINFO_WIFI		        39813	//WIFI模块
#define		ID_STR_DLG_DEVINFO_CK_VIDEOLOST		39814	//视频丢失
#define		ID_STR_DLG_DEVINFO_DISK_INFO		39815	//硬盘信息
#define		ID_STR_DLG_DEVINFO_RECORD_STATE		39816	//录像状态
#define		ID_STR_DLG_DEVINFO_RECORD_TRS_COU	39817	//视频传输数目
#define		ID_STR_DLG_DEVINFO_REFRESH      	39818	//刷新
#define     ID_STR_DLG_DEVINFO_VERSION          39819   //版本
#define     ID_STR_DLG_DEVINFO_YES              39820   //是  
#define     ID_STR_DLG_DEVINFO_NO               39821   //否 
#define     ID_STR_DLG_DEVINFO_RECORD           39822   //录像  
#define     ID_STR_DLG_DEVINFO_LOSS             39823   //录像丢失
#define     ID_STR_DLG_DEVINFO_3G_WIFI_YES      39824   //模块有效  
#define     ID_STR_DLG_DEVINFO_3G_WIFI_NO       39825   //模块无效

#define     ID_STR_DLG_DEVINFO_CHANNEL_NORMAL			39826   //正常通道
#define     ID_STR_DLG_DEVINFO_CHANNEL_UNUSED			39827   //未使用通道
#define     ID_STR_DLG_DEVINFO_CHANNEL_RECORDING		39828   //通道正在录像
#define     ID_STR_DLG_DEVINFO_CHANNEL_REQUED_RECORD    39829   //通道正在请求录像
#define     ID_STR_DLG_DEVINFO_CHANNEL_RECORD_ERROR     39830   //通道录像不正常

#define     ID_STR_DLG_DEV_PROMOTE_TITLE        39900   //设备升级
#define     ID_STR_DLG_DEV_PROMOTE_SUCC         39901   //升级完成
#define     ID_STR_DLG_DEV_PROMOTE_FAIL         39902   //升级失败
#define     ID_STR_DLG_DEV_PROMOTE_FILE_VERSION 39903   //版本信息
#define     ID_STR_DLG_DEV_PROMOTE_DEV_TYPE     39904   //设备类型
#define     ID_STR_DLG_DEV_PROMOTE_NOTE         39905   //升级文件版本信息有误，请重新选择正确的升级文件
#define     ID_STR_DLG_DEV_PROMOTE_NO           39906   //未升级
#define     ID_STR_DLG_DEV_PROMOTE_DEV_NAME     39907   //设备名称
#define     ID_STR_DLG_DEV_PROMOTE              39908   //升级
#define     ID_STR_DLG_DEV_PROMOTE_STATE        39909   //完成状态
#define     ID_STR_DLG_DEV_PROMOTE_FILE         39910   //升级文件
#define     ID_STR_DLG_DEV_PROMOTE_LIST         39911   //设备升级列表
#define     ID_STR_DLG_DEV_PROMOTE_CLEAR        39912  //清空
#define     ID_STR_DLG_DEV_PROMOTE_PROCESS      39913  //升级进度
#define     ID_STR_DLG_DEV_PROMOTE_PROMPT       39914  //提示
#define     ID_STR_DLG_DEV_PROMOTE_TELL         39915  //该设备的类型与升级文件所能升级的设备的类型不一致
#define     ID_STR_DLG_DEV_PROMOTE_FILE_SEL     39916  //请选择升级文件!
#define     ID_STR_DLG_DEV_PROMOTE_DEV_SEL      39917  //请选择要升级的设备!
#define     ID_STR_DLG_DEV_PROMOTE_STOP         39918  //确实要停止设备升级?
#define     ID_STR_DLG_DEV_STOP                 39919  //停止升级
#define     ID_STR_DLG_DEV_PROMOTE_FILE_NOTE    39920  //升级文件上传状态:
#define     ID_STR_DLG_DEV_PROMOTE_NOTE_SUCC    39921  //升级文件上传状态:上传升级文件到服务器成功!
#define     ID_STR_DLG_DEV_PROMOTE_FILE_STOP    39922  //是否要停止上传升级文件?
#define		ID_STR_DLG_DEV_PROMOTE_ERR       	39923	//设备升级失败！错误原因：
#define		ID_STR_DLG_DEV_PROMOTE_FILE_STOP_DW 39924	//升级文件停止上传
#define     ID_STR_DLG_DEV_PROMOTE_FAR_END      39925   //远端设备正在升级
#define     ID_STR_DLG_DEV_UP_VER_SAME_ERROR     39926	//升级文件版本与设备版本相同，不执行升级操作
#define     ID_STR_DLG_DEV_UP_FILE_ERROR         39927	//升级文件不存在或损坏不可读
#define     ID_STR_DLG_DEV_DEV_UP_FILE_CRC_ERROR 39928   ///升级文件crc校验失败
#define     ID_STR_DLG_DEV_UP_VER_FAILED_ERROR   39929	//不能从当前版本升级到目标版本
#define     ID_STR_DLG_DEV_UP_FAILED_ERROR       39930	//升级失败
#define     ID_STR_DLG_DEV_UNKNOW_ERROR          39931	//未知错误
#define     ID_STR_DLG_DEV_PROMOTE_NO_GET        39932   //无法获取升级文件类型
#define     ID_STR_DLG_DEV_PROMOTE_TIP           39933   //请您重新添加升级文件!
#define     ID_STR_DLG_DEV_UP_FILE               39934	//正在上传文件
#define     ID_STR_DLG_DEV_UP_CUCC_TIP           39935   //成功上传升级文件到设备,设备将在重启后进行升级
#define     ID_STR_DLG_DEV_PROMOTE_READY         39936   //准备升级
#define     ID_STR_DLG_DEV_PROMOTE_INFO          39937   //升级文件名称为:

#define     ID_STR_DEV_UP_UPGRADING              40001  //正在升级
#define     ID_STR_ERR_DEV_UP_FILE_WRONG        40002  //升级文件不正确
#define     ID_STR_ERR_DEV_UP_VER_LOW           40003  //升级文件版本过低
#define     ID_STR_ERR_DEV_UP_VERIFY_FAILED     40004  //升级文件校验失败
#define     ID_STR_ERR_DEV_CHN_NO_EXIST         40005  //通道信息不存在
#define     ID_STR_ERR_DEV_SNAP_JPG             40006  //抓拍图片失败
#define     ID_STR_ERR_DEV_DISK_FULL            40007  //硬盘空间不足
#define     ID_STR_ERR_SVR_DISK_FULL            40008  //服务器空间不足
#define     ID_STR_ERR_SVR_BUSY                 40009  //服务器忙
#define     ID_STR_ERR_SVR_CREATE_FILE          40010  //服务器创建文件失败
#define     ID_STR_ERR_NOTI_SERVER_NO_EXIST     40011  //通知服务器不存在
#define     ID_STR_ERR_NOTI_SERVER_LINK_FAIL    40012  //通知服务器连接失败
#define     ID_STR_ERR_MESS_SERVER_NO_START     40013  //短信模块服务没有启动

#define		ID_STR_DLG_EXPIRED_TIP_USER_RELOGIN	50001	//用户已删除！	
#define		ID_STR_DLG_EXPIRED_TIP_USER_EXPIRED	50002	//用户已过期！
#define		ID_STR_DLG_EXPIRED_TIP_VER_ERR		50003	//版本信息不匹配！	
#define		ID_STR_DLG_EXPIRED_TIP_CMP_ERR		50004	//公司信息有误！
#define		ID_STR_DLG_EXPIRED_TIP_EXIST	    50005	//用户已登录!
#define		ID_STR_DLG_EXPIRED_TIP_FULL_ERR		50006	//服务器用户满！
#define		ID_STR_DLG_EXPIRED_TIP_CNT_ERR		50007	//无法连接服务器！
#define     ID_STR_DLG_EXPIRED_TIP_FULL_EMPTY_ERR 50008 //不存在用户服务器信息
#define		ID_STR_DLG_EXPIRED_TIP_USER_DEL		50009	//用户已删除！
#define		ID_STR_DLG_EXPIRED_TIP_USER_PRIVILEGE_CHANGE 50010 //用户权限发生变化
#define		ID_STR_DLG_EXPIRED_TIP_SVR_CONFIG_CHANGE 50011 //服务器配置信息发生变化

#define     ID_STR_DLG_PARAMER_TIP_GET          60001  //正在获取设备参数信息，请稍等......
#define     ID_STR_DLG_PARAMER_GET_FAILT        60002  //获取设备参数失败!
#define     ID_STR_DLG_PARAMER_GET_SUCC         60003  //获取设备参数成功!
#define     ID_STR_DLG_PARAMER_UP_FILE          60004  //正在上传配置文件，请稍等......
#define     ID_STR_DLG_PARAMER_UP_SUCC          60005  //上传配置文件到服务器成功!
#define     ID_STR_DLG_PARAMER_DOWN_FAILT       60006  //下传配置参数文件失败!
#define     ID_STR_DLG_PARAMER_CONFIG           60007  //配置
#define     ID_STR_DLG_PARAMER_CONFIG_FINSH     60008  //配置已完成!
#define     ID_STR_DLG_PARAMER_TIP_DOWN         60009  //正在下传配置文件,请稍等......
#define     ID_STR_DLG_PARAMER_DOWN_STOP        60010  //下传配置停止!
#define     ID_STR_DLG_PARAMER_UP_STOP          60011  //停止上传配置文件!
#define     ID_STR_DLG_PARAMER_STOP_CONFIG      60012  //停止配置
#define     ID_STR_DLG_PARAMER_SAVE_MORE        60013  //保存到多个设备
#define     ID_STR_DLG_PARAMER_WINDOW_NAME      60014  //车辆参数配置
#define     ID_STR_DLG_PARAMER_WARN             60015  //列表没有可配置的设备!
#define     ID_STR_DLG_PARAMER_CONFIG_NO        60016  //未配置
#define     ID_STR_DLG_PARAMER_IS_STOP_UP       60017  //是否停止上传配置文件到服务器?
#define     ID_STR_DLG_PARAMER_IS_STOP_DOWN     60018  //是否要停止下传配置文件到设备?
#define     ID_STR_DLG_PARAMER_CONFIG_SUCC      60019  //配置成功
#define     ID_STR_DLG_PARAMER_SEL_DEV          60020  //选择设备
#define     ID_STR_DLG_PARAMER_DOWN_SUCC        60021  //下传配置文件到设备成功!
#define     ID_STR_DLG_PARAMER_IS_GET_PARAMER   60022  //是否停止获取设备参数?
#define     ID_STR_DLG_PARAMER_PARPARE          60023  //准备配置
#define     ID_STR_DLG_PARAMER_EXPORT           60024  //导出配置
#define     ID_STR_DLG_PARAMER_IMPORT           60025  //导人配置
#define     ID_STR_DLG_PARAMER_UP_STAUE         60026  //配置文件上传状态:
#define     ID_STR_DLG_PARAMER_TIP              60027  //提示:设备参数无修改,不会配置设备参数!
#define     ID_STR_DLG_PARAMER_STATIC_FILE_CHOSE  60028  //请选择配置方式
#define     ID_STR_DLG_PARAMER_RADIO_CHANGE       60029  //配置设备修改了的参数
#define     ID_STR_DLG_PARAMER_RADIO_ALL          60030  //配置设备全部参数
#define     ID_STR_DLG_PARAMER_CHA_UP_SUCC      60031  //设备参数改变的配置已经完成!
#define     ID_STR_DLG_PARAMER_ALL_UP_SUCC      60032  //设备全部参数已经配置完成!
#define     ID_STR_DLG_PARAMER_WARN_DISK        60033  //此功能目前只支持卡机设备，暂不支持硬盘机设备!
#define     ID_STR_DLG_PARAMER_INPUT_SUC        60034  //导入参数配置文件成功！
#define     ID_STR_DLG_PARAMER_EXPORT_SUC       60035  //导出参数配置文件成功！

#define     ID_STR_DLG_CSM_SEND_TIP_PORT_ERROR  61000  //端口有误，范围1-65535，请重新输入！
#define     ID_STR_DLG_CSM_SEND_TIP_IP_ERROR    61001  //IP地址不合法，请重新输入！
#define     ID_STR_DLG_CSM_SEND_FRAM            61002  //车辆短信下发
#define     ID_STR_DLG_CSM_SEND_FORMAT          61003  //发送指令
#define     ID_STR_DLG_CSM_SEND_DEV_NUM         61004  //设备号
#define     ID_STR_DLG_CSM_SEND_RECEIVE         61005  //接收确认
#define     ID_STR_DLG_CSM_SEND_CHECK_RETURN    61006  //是否回复设备接收状态
#define     ID_STR_DLG_CSM_SEND_PHONE_TIP       61007  //手机号
#define     ID_STR_DLG_CSM_SEND_WARN_PHOME      61008  //请输入手机号!
#define     ID_STR_DLG_CSM_SEND_WARN_NUM        61009  //请输入设备号!
#define     ID_STR_DLG_CSM_SEND_WARN_SIM        61010  //设备SIM卡为空，将不能下发车辆短信!
#define     ID_STR_DLG_CSM_SEND_MOD_DEV         61011  //修改设备号
#define     ID_STR_DLG_CSM_SEND_GET_STATUS      61012  //获取设备状态
#define     ID_STR_DLG_CSM_SEND_MOD_CENTER_IP   61013  //修改中心IP
#define     ID_STR_DLG_CSM_SEND_3G_BH           61014  //3g拨号
#define     ID_STR_DLG_CSM_SEND_CONTENT         61015  //当前下发:
#define     ID_STR_DLG_CMS_SEND_ADD_DEV         61016  //设备列表没有下发的车辆，请添加!
#define     ID_STR_DLG_CMS_SEND_CONTENT         61017  //下发内容:
#define     ID_STR_DLG_CMS_SEND_DEV_SIM         61018  //设备Sim卡:
#define     ID_STR_DLG_CMS_SEND_SUCC            61019  //车辆短息下发成功
#define     ID_STR_DLG_CMS_SEND_FAIL            61020  //车辆短息下发失败
#define     ID_STR_DLG_CMS_SEND_IS_HAVE         61021  //请不要重复的添加该车辆
#define     ID_STR_DLG_CMS_SEND_OPEN            61022  //开启
#define     ID_STR_DLG_CMS_SEND_CLOSE           61023  //关闭
#define     ID_STR_DLG_CMS_SEND_CLOSE_DISPLAY   61024  //关闭延时
#define     ID_STR_DLG_CMS_SEND_REBOOT_DISPLAY  61025  //重启延时
#define     ID_STR_DLG_CMS_SEND_PORT            61026  //端口
#define     ID_STR_DLG_CMS_SEND_ENABLE_SEND     61027  //可手机短信下发
#define     ID_STR_DLG_CMS_SEND_TELL            61028  //下发说明
#define     ID_STR_DLG_CMS_SEMD_1               61029  //方式一:使用本平台下发
#define     ID_STR_DLG_CMS_SEND_2               61030  //方式二:用户可编辑短信下发
#define     ID_STR_DLG_CMD_SEND_3G_STATUS       61031  //3G状态

#define     ID_STR_DLG_CMS_STATISTIC_DEV_GROUP  62000  //车辆组
#define     ID_STR_DLG_CMS_STATISTIC_DEVGROUP   62001  //车辆/车辆组
#define     ID_STR_DLG_CMS_STAITSTIC_IP_PORT    62002  //终端IP/端口
#define     ID_STR_DLG_CMS_STAITSTIC_ONLINE     62003  //车辆上线
#define     ID_STR_DLG_CMS_STAITSTIC_OFFLINE    62004  //车辆下线
#define     ID_STR_DLG_CMS_STAITSTIC_LINE_ON_OFF    62005  //车辆上下线
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_ON     62006  //ACC开启
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_OFF    62007  //ACC关闭
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_ON_OFF 62008  //ACC开关闭
#define     ID_STR_DLG_CMS_STATICTIS_BTN_NUM    62009  //按钮编号
#define     ID_STR_DLG_CMS_STATICTIS_OTHER_NAME 62010  //别名
#define     ID_STR_DLG_CMS_STATISTIC_WARN_DOOR  62011  //报警门
#define     ID_STR_DLG_CMS_STATISTIC_EXCEPT_DES 62012  //异常描述
#define     ID_STR_DLG_CMS_STATISTIC_DISK_NUM   62013  //硬盘号
#define     ID_STR_DLG_CMS_STATISTIC_ERR_DES    62014  //错误描述
#define     ID_STR_DLG_CMS_STATISTIC_WARN_CA    62015  //报警类别
#define     ID_STR_DLG_CMS_STATISTIC_FENCE_NUM  62016  //围栏号
#define     ID_STR_DLG_CMS_STATISTIC_WARN_NUM   62017  //报警编号
#define     ID_STR_DLG_CMS_STATISTIC_WARN_SOURCE     62018  //报警源
#define     ID_STR_DLG_CMS_STATISTIC_WARN_NAME       62019  //报警名称
#define     ID_STR_DLG_CMS_STATISTIC_WARN_SPEED      62020  //报警速度
#define     ID_STR_DLG_CMS_STATISTIC_WARN_MIN_SPEED  62021  //最低速度
#define     ID_STR_DLG_CMS_STATISTIC_WARN_MAX_SPEED  62022  //最高速度

#define     ID_STR_DLG_CMS_STATISTIC_DEV_ON_OFF_REPORT  62023 //车辆上下线报表
#define     ID_STR_DLG_CMS_STATISTIC_DEV_ON_OFF_STAITS  62024 //车辆上下线统计
#define     ID_STR_DLG_CMS_STATISTIC_ACC_REPORT         62025 //ACC报表
#define     ID_STR_DLG_CMS_STATISTIC_ACC_STATISTIC      62026 //ACC统计
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_REPORT       62027 //视频报表
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_NO_SIGNAL    62028 //视频无信号
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_HIDE         62029 //视频遮挡
#define     ID_STR_DLG_CMS_STATISTIC_SPEED_REPORT       62030 //速度报表
#define     ID_STR_DLG_CMS_STATISTIC_SPEED_CURVE        62031 //速度曲线
#define     ID_STR_DLG_CMS_STATISTIC_OVER_SPEED_REPORT  62032 //超速报表
#define     ID_STR_DLG_CMS_STATISTIC_ORTHER_REPORT_STAT 62033 //其他报表统计
#define     ID_STR_DLG_CMS_STATISTIC_CUSTOM_WARN        62034 //自定义报警
#define     ID_STR_DLG_CMS_STATISTIC_EME_BUT_WARN       62035 //紧急按钮报警
#define     ID_STR_DLG_CMS_STATISTIC_SHOCK_WARN         62036 //震动报警
#define     ID_STR_DLG_CMS_STATISTIC_ILLEAGL_OPEN_WARN  62037 //非法开门报警
#define     ID_STR_DLG_CMS_STATISTIC_THREE_ERR_WARN     62038 //三次密码错误报警
#define     ID_STR_DLG_CMS_STATISTIC_DISK_ERR_WARN      62039 //硬盘错误报警
#define     ID_STR_DLG_CMS_STATISTIC_ABNORM_ONOFF_WARN  62040 //异常开关门报警
#define     ID_STR_DLG_CMS_STATISTIC_CROSS_WARN         62041 //越界报警
#define     ID_STR_DLG_CMS_STATISTIC_ABNORMAL_FIRE_WARN 62042 //非法点火报警
#define     ID_STR_DLG_CMS_STATISTIC_SET_DATE_TIP       62043 //提示:支持查询某一个月的信息,查询的结果为起始时间的那个月的时间段内的数据!
#define     ID_STR_DLG_CMS_STATISTIC_TIP_DATE_TELL      62044 //提示:支持查询某一个月的信息
#define     ID_STR_DLG_CMS_STATISTIC_TIP_DATE_TELL_WARN 62045 //,本次查询结果为%d月份内的查询时间段内的数据!;
#define     ID_STR_DLG_CMS_STATISTIC_VEHICLE_POS        62046 //查看车辆位置



#define     ID_STR_CMS_BRAKE                        63000 //刹车
#define     ID_STR_CMS_LEFT                         63001 //左转
#define     ID_STR_CMS_RIGHT                        63002 //右转
#define     ID_STR_CMS_POSITIVE                     63003 //转正
#define     ID_STR_CMS_REVERSE                      63004 //反转
#define		ID_STR_DESC_PARK_LAST_TIME		        63005 //停车时长：
#define		ID_STR_DESC_PARK_SETUP_TIME		        63006 //设定时长：
#define     ID_STR_CMS_GPS_VALID                    63007 //GPS定位有效
#define     ID_STR_CMS_GPS_INVALID                  63008 //GPS定位无效
#define     ID_STR_CMS_GPS_ANTENNA_VALID            63009 //GPS天线有效
#define     ID_STR_CMS_GPS_ANTENNA_NORMAL           63010 //GPS天线存在
#define     ID_STR_CMS_GPS_ANTENNA_INVALID          63011 //GPS天线不存在
#define     ID_STR_CMS_GPS_DISK_NOT_EXIST           63012 //硬盘不存在
#define     ID_STR_CMS_GPS_DISK_EXIST               63013 //硬盘存在
#define     ID_STR_CMS_GPS_DISK_DISCONNECT_POWER    63014 //硬盘断电
#define     ID_STR_CMS_3G_NOT_EXIST                 63015 //3G模块不存在
#define     ID_STR_CMS_3G_NO_SIGNAL                 63016 //3G无信号
#define     ID_STR_CMS_3G_SIGNAL_POOR               63017 //3G信号差
#define     ID_STR_CMS_3G_SIGNAL_GENERAL            63018 //3G信号一般
#define     ID_STR_CMS_3G_SIGNAL_GOOD               63019 //3G信号好
#define     ID_STR_CMS_3G_SIGNAL_EXCELLENT          63020 //3G信号优
#define     ID_STR_CMS_SFM_TIP                      63021 //(%d小时%d分%d秒)
#define     ID_STR_CMS_FM_TIP                       63022 //(%d分%d秒)
#define     ID_STR_CMS_M_TIP                        63023 //(%d秒)
#define     ID_STR_CMS_DEVICE_STATIC                63024 //停车
#define     ID_STR_CMS_DEVICE_OVER_SPEED            63025 //超速
#define     ID_STR_CMS_3G_SIGNAL_CLOSE		        63026 //3G功能关闭
#define     ID_STR_CMS_3G_SIM_NOT_EXIST		        63027 //SIM卡不存在
#define     ID_STR_CMS_GPS_DISK						63028 //硬盘
#define     ID_STR_CMS_GPS_NOT_EXIST				63029 //不存在
#define     ID_STR_CMS_GPS_EXIST					63030 //存在
#define     ID_STR_CMS_GPS_DISCONNECT_POWER			63031 //断电
#define     ID_STR_CMS_3G_SIGNAL_WEAK		        63032 //信号弱
#define     ID_STR_CMS_GPS_SD						63033 //SD卡
#define     ID_STR_CMS_GPS_SSD						63034 //SSD

#define     ID_STR_UP_3G_INTERVAL              64000 //上报间隔设置
#define     ID_STR_UP_3G_INTERVAL_TIME_FW      64001 //(3-3600秒)
#define     ID_STR_UP_3G_INTERVAL_WARN_EMPTY   64002 //Gps上报的时间间隔不能为空!
#define     ID_STR_UP_3G_INTERVAL_BETWEEN      64003 //上报Gps时间间隔介于%d-%d之间!
#define     ID_STR_UP_3G_INTERVAL_SET          64004 //GPS上报间隔设置
#define     ID_STR_UP_GPS_INTERVAL_FAIL        64005 //GPS上报间隔设置失败
#define     ID_STR_UP_GPS_INTERVAL_SUCC        64006 //GPS上报间隔设置成功
#define     ID_STR_UP_GPS_INTERVAL_TIP         64007 //GPS上报间隔:
#define     ID_STR_UP_GPS_UNIT                 64008 //秒

#define     ID_STR_DLG_STATISTIC_BUT_BIG         65000  //放大
#define     ID_STR_DLG_STATISTIC_BUT_SMALL       65001  //缩小
#define     ID_STR_DLG_STATISTIC_BUT_MOVE_LEFT   65002  //左移动
#define     ID_STR_DLG_STATISTIC_BUT_MOVE_RIGHT  65003  //右移动
#define     ID_STR_DLG_STATISTIC_BUT_PRINT       65004  //打印
#define     ID_STR_DLG_STATISTIC_STATIC_TEEL_TIP 65005  //------->温馨提示：由于查询的数据点比较多,可能需要点时间!
#define     ID_STR_DLG_STATISTIC_BUT_QUERY       65006  //查询
#define     ID_STR_CMS_STATTISTIC_SPEED_CURVE    65007 //正在搜索速度曲线，确定要重新查询速度曲线?
#define     ID_STR_CMS_STATISTIC_RE_QUERY        65008 //重新查询
#define     ID_STR_CMS_STATISTIC_TIP_FOR         65009 //"拖动鼠标可放大曲线、也可以通过鼠标滑轮缩放曲线";
#define     ID_STR_CMS_STATISTIC_SPEEDTIME_TIP   65010 //速度曲线

#define     ID_STR_DLG_STATISTIC_SPEED_CURVE_PAGE_SET   65011  //纸张设置
#define     ID_STR_DLG_STATISTIC_STATIC_SET             65012  //设置打印风格
#define     ID_STR_DLG_STATISTIC_RADIO_HENG             65013  //横向打印
#define     ID_STR_DLG_STATISTIC_RADIO_ZONG             65014  //纵向打印
#define     ID_STR_DLG_STATISTIC_BTN_SET                65015  //设置
#define     ID_STR_DLG_STATISTIC_TELL_TIP               65016  //无数据可打印   

#define     ID_STR_DLG_CHANNEL_GROUP_WARN_EMPTY  66000    //分组名称不能为空!
#define     ID_STR_DLG_CHANNEL_GROUP_WARN_HAVE   66001    //分组名称已经存在!
#define     ID_STR_DLG_CHANNEL_GROUP_ADD         66002    //添加分组
#define     ID_STR_DLG_CHANNEL_GROUP_NAME        66003    //分组名称
#define     ID_STR_DLG_CHANNEL_GROUP_TIP         66004    //提示--->右键添加通道分组
#define     ID_STR_DLG_CHANNEL_GROUP_CONFIG      66005    //分组配置
#define     ID_STR_DLG_CHANNEL_GROUP_DEV_LIST    66006    //设备列表
#define     ID_STR_DLG_CHANNEL_GROUP_TO          66007    //通道分组
#define     ID_STR_DLG_CHANNEL_GROUP_ADD_WARN    66008   //请添加分组!  
#define     ID_STR_DLG_CHANNEL_GROUP_DEV_SL_WARN 66009   //请选择设备或通道!
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_WARN    66010   //无可删除的分组或通道!
#define     ID_STR_DLG_CHANNEL_GROUP_SEL_WARN    66011   //请在右边的树中选择一个分组或通道!
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_GROUP   66012   //删除分组
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_DEV     66013   //删除设备
#define     ID_STR_DLG_CHANNEL_GROUP_POLLING     66014   //轮询分组%s正在轮询，是否要删除
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_TIP     66015   //是否要删除轮询分组%s!
#define     ID_STR_DLG_CHANNEL_GROUP_POLL_WND    66016   //轮询分组%s正在窗口%d上轮询!
#define     ID_STR_DLG_CHANNEL_TELL_TIP          66017   //温馨提示:分组名称无重复,每个分组下的设备通道无重复!
#define		ID_STR_DLG_CHANNEL_GROUP_ITEM_TIP	 66018	 //温馨提示:\t\n拖动节点到视频窗口开启轮询.
#define		ID_STR_DLG_CHANNEL_GROUP_ITEM_TIP2	 66019	 //拖动节点到视频窗口开启轮询.

#define     ID_STR_DLG_MOTION_CONFIG             67000   //移动侦测配置
#define     ID_STR_DLG_MOTION_ENABLE             67001   //使能
#define     ID_STR_DLG_MOTION_OPEN               67002   //开
#define     ID_STR_DLG_MOTION_CLOSE              67003   //关
#define     ID_STR_DLG_MOTION_SENEITIVE          67004   //灵敏度
#define     ID_STR_DLG_MOTION_LOW                67005   //低
#define     ID_STR_DLG_MOTION_MIDDLE             67006   //中
#define     ID_STR_DLG_MOTION_HIGH               67007   //高
#define     ID_STR_DLG_MOTION_TOP_TIP            67008   //根据鼠标拖动,选择要配置的方格区域!
#define     ID_STR_DLG_MOTION_GET_P_SUCC         67009   //抓拍图片成功! 
#define     ID_STR_DLG_MOTION_GETTING_P_NOW      67010   //正在获取抓拍图片,请稍等......
#define     ID_STR_DLG_MOTION_CONFIG_STOP        67011   //移动侦测配置停止!
#define     ID_STR_DLG_MOTION_GET_INFO           67012   //正在获取移动侦测信息，请等待......
#define     ID_STR_DLG_MOTION_GET_INFO_SUCC      67013   //获取移动侦测信息成功!
#define     ID_STR_DLG_MOTION_CONFIGING_NOW      67014   //正在配置移动侦测信息，请等待......
#define     ID_STR_DLG_MOTION_CONFIG_SUCC        67015   //移动侦测信设置成功!
#define     ID_STR_DLG_MOTION_CLEAR              67016   //清空填充
#define     ID_STR_DLG_MOTION_GET_INFO_FAILT     67017   //获取移动侦测信息失败!

#define     ID_STR_DLG_3G_FLOW_STATISTIC         68000   //3G流量统计
#define     ID_STR_DLG_3G_FLOW_CONFIG            68001   //3G流量配置
#define     ID_STR_DLG_3G_FLOW_PAY_SYSTEM        68002   //具体流量数据以运营商的计费系统为准
#define     ID_STR_DLG_3G_FLOW_CURRENT_USE       68003   //当前已用流量
#define     ID_STR_DLG_3G_FLOW_CURRENT_MONTH     68004   //当月已用流量
#define     ID_STR_DLG_3G_FLOW_DAY_LIMIT         68005   //日流量限制
#define     ID_STR_DLG_3G_FLOW_MONTH_LIMIT       68006   //月流量限制
#define     ID_STR_DLG_3G_FLOW_USED_STATUS       68007   //GPRS/3G使用状态
#define     ID_STR_DLG_3G_FLOW_TODAY_USE         68008   //今日已用
#define     ID_STR_DLG_3G_FLOW_UNIT              68009   //兆
#define     ID_STR_DLG_3G_FLOW_CURRENT_MONTH_USE 68010   //本月已用
#define     ID_STR_DLG_3G_FLOW_CURRENT_DAY_USE   68011   //本月剩余
#define     ID_STR_DLG_3G_FLOW_CURRENT_LIMIT     68012   //本月限额
#define     ID_STR_DLG_3G_FLOW_CON_PAY_DAY       68013   //据结算日
#define     ID_STR_DLG_3G_FLOW_SET               68014   //流量设置
#define     ID_STR_DLG_3G_FLOW_MONTH_PACKAGE     68015   //每月套餐限额
#define     ID_STR_DLG_3G_FLOW_MONTH_USE_TELL    68016   //每月流量提醒
#define     ID_STR_DLG_3G_FLOW_PAY_DAY           68017   //结算日
#define     ID_STR_DLG_3G_FLOW_DAY_TELL          68018   //每日提醒
#define     ID_STR_DLG_3G_FLOW_MONTOR_ENABLE     68019   //开启流量监控
#define     ID_STR_DLG_3G_FLOW_ADJUST            68020   //数据校正
#define     ID_STR_DLG_3G_FLOW_CLEAR_DATA        68021   //清空统计数据
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_SUCC  68022   //获取设备3G信息成功!
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_FAIL  68023   //获取设备3G信息失败!原因:
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_WAIT  68024   //正在获取设备3G信息，请等待......
#define     ID_STR_DLG_3G_FLOW_SET_3G_INFO_SUCC  68025   //设置设备3G信息设置成功!
#define     ID_STR_DLG_3G_FLOW_SET_3G_INFO_FAIL  68026   //设置设备3G信息失败!原因:
#define     ID_STR_DLG_3G_FLOW_MONTH_BETWEEN_TIP 68027   //月结日介于1到31之间!请重新输入! 
#define     ID_STR_DLG_3G_FLOW_TH                68028   //日
#define     ID_STR_DLG_3G_FLOW_DAY               68029   //天  
#define     ID_STR_DLG_3G_FLOW_NO_STATISTIC_DEV  68030   //没有可统计的在线车辆!
#define     ID_SRE_DLG_3G_FLOW_ADJUST_SUCC       68031   //校验设置成功
#define     ID_SRE_DLG_3G_FLOW_ADJUST_FAIL       68032   //校验设置成功
#define     ID_SRE_DLG_3G_FLOW_ADJUST            68033   //校验
#define     ID_SRE_DLG_3G_FLOW_ADJUST_STOP       68034   //停止校验
#define     ID_SRE_DLG_3G_FLOW_ADJUST_VALUE_WARN 68035   //请输入校验值介于0-10240之间!
#define     ID_STR_DLG_3G_FLOW_MANUAL            68036   //手动校验
#define		ID_STR_DLG_3G_FLOW_DAY_REMINDE			 68037	 //日流量提醒
#define		ID_STR_DLG_3G_FLOW_OPEN_DAY_REMINDE		 68038	 //开启每日提醒
#define		ID_STR_DLG_3G_FLOW_OPEN_MONTH_REMINDE	68039	//开启每月提醒
#define		ID_STR_DLG_3G_FLOW_MONTH_REMINDE			 68040	 //月流量提醒
#define		ID_STR_DLG_3G_FLOW_REMINDE				68041		//流量提醒
#define     ID_STR_DLG_3G_FLOW_MONTH_FLOW_TIP	68042   //每月套餐限额介于0到1024000之间!请重新输入! 
#define     ID_STR_DLG_3G_FLOW_DALY_FLOW_TIP	68043   //每日限额介于0到1024000之间!请重新输入! 
#define     ID_STR_DLG_3G_FLOW_DAY_FLOW_REMIND_TIP	68044   //每日流量提醒介于0到99之间!请重新输入! 
#define     ID_STR_DLG_3G_FLOW_MONTH_FLOW_REMIND_TIP	68045   //每月流量提醒介于0到99之间!请重新输入! 

#define     ID_STR_DLG_ALARM_SHIELD              69000   //报警屏蔽配置
#define     ID_STR_DLG_ALARM_SHIELD_CONFIG_SUC   69001   //报警屏蔽配置成功!
#define     ID_STR_DLG_ALARM_SHIELD_CONFIG_FIAL  69002   //报警屏蔽配置失败!

#define     ID_STR_MY_MAP                        69100   //我的地图
#define     ID_STR_MY_MAP_NAME                   69101   //名称
#define     ID_STR_MY_MAP_TYPE                   69102   //类型
#define     ID_STR_MY_MAP_DD				     69103   //地点 
#define     ID_STR_MY_MAP_MENU_MODIFY_DEV        69104   //修改关联设备
#define     ID_STR_MY_MAP_MENU_MODIFY_FENCE      69105   //修改区域
#define     ID_STR_MY_MAP_MENU_ADD_FENCE         69106   //添加区域
#define     ID_STR_MY_MAP_MENU_DEL_FENCE         69107   //删除区域
#define		ID_STR_MY_MAP_MENU_DEL_ALL			 69108	 //删除所有的区域
#define		ID_STR_MY_MAP_POINT					 69109	 //点
#define		ID_STR_MY_MAP_LINE					 69110	 //线
#define		ID_STR_MY_MAP_MARKE					 69111	 //面


#define     ID_STR_DLG_ALARM_IO_TIP              69200   //%s报警
#define     ID_STR_DLG_IO_ALAEM                  69201   //IO报警
#define     ID_STR_DLG_MOTION_UNIT_DC            69202  //摄氏度
#define     ID_STR_DLG_PANE_MAP_ALARM_POINT      69203  //报警点



#define		ID_STR_DLG_TOP_TAG_BTN_MAN			 69300	 //首页
#define		ID_STR_DLG_TOP_TAG_BTN_TRACK_BACK	 69301	 //轨迹回放
#define		ID_STR_DLG_TOP_TAG_BTN_FULL_SRCEEN	 69302	 //全屏
#define		ID_STR_DLG_TOP_TAG_BTN_VIDEO_WND	 69303	 //视频
#define		ID_STR_DLG_TOP_TAG_BTN_REBOOT		 69304	 //注销
#define		ID_STR_DLG_TOP_TAG_BTN_MIN			 69305	 //最小化
#define		ID_STR_DLG_TOP_TAG_BTN_EXIT			 69306	 //退出
#define		ID_STR_DLG_TOP_TAG_BTN_REBOOT_MSG	 69307	 //确定要切换用户登录?
#define		ID_STR_DLG_TOP_TAG_BTN_EXIT_MSG		 69308	 //确定要退出系统?
#define		ID_STR_DLG_TOP_TAG_BTN_MAP			 69309	 //电子地图
#define		ID_STR_DLG_TOP_TAG_BTN_VIDEO		 69310	 //实时预览
#define		ID_STR_DLG_TOP_TAG_BTN_RECORD_BACK	 69311	 //录像查询
#define		ID_STR_DLG_TOP_TAG_BTN_REPORT		 69312	 //报表统计
#define		ID_STR_DLG_TOP_TAG_BTN_OTHER		 69313	 //其他应用
#define		ID_STR_PTZ_SPEED					 69314	 //- 速度 +
#define		ID_STR_DLG_TOP_TAG_BTN_REPOSITION_MAX		69315	 //最大化
#define		ID_STR_DLG_TOP_TAG_BTN_REPOSITION_NORMAL	 69316	 //还原
#define		ID_STR_DLG_OHTER_SET_BTN_WEB_CLIENT	 69317	 //报表查询

#define		ID_STR_DLG_MARKER_POINT_TITLE		69401	//添加自定义点
#define		ID_STR_DLG_MARKER_POINT_ST_TYPE		69402	//类型
#define		ID_STR_DLG_MARKER_POINT_ST_JINGDU	69403	//经度
#define		ID_STR_DLG_MARKER_POINT_ST_WEIDU	69404	//纬度
#define		ID_STR_DLG_MARKER_POINT_ST_NAME		69405	//名称
#define		ID_STR_DLG_MARKER_POINT_ST_REMARKS	69406	//描述
#define		ID_STR_DLG_MARKER_POINT_NAME_EMPTY	69407	//名称不得为空
#define		ID_STR_DLG_MARKER_POINT_ST_SHARE	69408	//共享
#define		ID_STR_DLG_MARKER_POINT_CHK_SHARE	69409	//允许其它用户查看
#define		ID_STR_DLG_MARKER_RECT_TITLE		69410	//添加矩形
#define		ID_STR_DLG_MARKER_POLYGON_TITLE		69411	//添加多边形
#define		ID_STR_DLG_MARKER_POINT_ST_QIDIAN	69412	//起点
#define		ID_STR_DLG_MARKER_POINT_ST_ZHONGDIAN	69413	//终点
#define		ID_STR_DLG_MARKER_LINE_TITLE		69414	//添加线路
#define		ID_STR_DLG_MARKER_ADD_FAILED		69415	//添加失败

#define		ID_STR_MARKER_TYPE_CAMP				69419	//营地
#define		ID_STR_MARKER_TYPE_VILLAGE			69420	//村庄
#define		ID_STR_MARKER_TYPE_FACTORY			69421	//工厂
#define		ID_STR_MARKER_TYPE_GONGDI			69422	//工地
#define		ID_STR_MARKER_TYPE_WAREHOURSE		69423	//仓库
#define		ID_STR_MARKER_TYPE_PIER				69424	//码头
#define		ID_STR_MARKER_TYPE_WULIU			69425	//物流园
#define		ID_STR_MARKER_TYPE_SHOUFEI			69426	//收费站
#define		ID_STR_MARKER_TYPE_TRACKPOINT		69427	//跟踪点
#define		ID_STR_MARKER_TYPE_OTHER			69428	//其它
#define		ID_STR_DEV_MOBLIE					69429	//手机
#define		ID_STR_MAP_CONFIG					69430	//地图配置
#define		ID_STR_MAP_CONFIG_ZOOM				69431	//缩放级别
#define		ID_STR_MAP_CONFIG_SUC				69432	//地图中心点配置成功
#define		ID_STR_MAP_CONFIG_CENTER_SURE		69433	//确定要把当前地图位置配置为默认地图启动位置吗？

#define		ID_STR_PANE_MAP_SEARCH_PARTNER		69500	//搜索队友和资源
#define		ID_STR_PANE_MAP_SEARCH_RES			69501	//搜索资源
#define		ID_STR_PANE_MAP_SEARCH_DISTANCE		69502	//距离(米)
#define		ID_STR_PANE_MAP_SEARCH_RADIUS		69503	//搜索半径
#define		ID_STR_PANE_MAP_SEARCH_MAN_NUM		69504	//民兵数量
#define		ID_STR_PANE_MAP_SEARCH_EUQ_NUM		69505	//灭火器数量
#define		ID_STR_PANE_MAP_SEARCH_SEND_MSG		69506	//发送短信
#define		ID_STR_PANE_MAP_SEARCH_SEND_CMD		69507	//发送调度命令
#define		ID_STR_PANE_MAP_SEARCH				69508	//重新搜索
#define		ID_STR_PANE_MAP_SEARCH_PIC			69509	//个
#define		ID_STR_PANE_MAP_SEARCH_MI			69510	//米
#define		ID_STR_PANE_MAP_SEARCH_MAN			69511	//民兵
#define		ID_STR_PANE_MAP_SEARCH_EUQ			69512	//灭火器
#define		ID_STR_PANE_SEND_CMD_SENDING		69513	//发送中...
#define		ID_STR_PANE_SEND_CMD_SEND_SUC		69514	//成功
#define		ID_STR_PANE_SEND_CMD_SEND_FAILED	69515	//失败
#define		ID_STR_PANE_SEND_CMD_SEND_STATUS	69516	//发送状态
#define		ID_STR_PANE_ALARM_TYPE				69517	//警情类型
#define		ID_STR_PANE_ALARM_MAN				69518	//报警人员
#define		ID_STR_PANE_ALARM_IMAGE_SHOW		69519	//查看报警图片
#define		ID_STR_PANE_ALARM_IMAGE_SHOW_FAIL		69520	//获取图片失败.
#define		ID_STR_PANE_ALARM_IMAGE_SHOW_LOADING		69521	//正在加载图片...



#define		ID_STR_WEEK_1						70000	//一
#define		ID_STR_WEEK_2						70001	//二
#define		ID_STR_WEEK_3						70002	//三
#define		ID_STR_WEEK_4						70003	//四
#define		ID_STR_WEEK_5						70004	//五
#define		ID_STR_WEEK_6						70005	//六
#define		ID_STR_WEEK_7						70006	//日

#define		ID_STR_CFG_GET_SUC					70050	//获取参数成功.
#define		ID_STR_CFG_GET_FAILED				70051	//获取参数失败.
#define		ID_STR_CFG_SET_SUC					70052	//设置参数成功.
#define		ID_STR_CFG_SET_FAILED				70053	//设置参数失败.
#define		ID_STR_CFG_SET_ING					70054	//设置参数中...
#define		ID_STR_CFG_GET_ING					70055	//获取参数中...

#define		ID_STR_CFG_AUDIO_INPUT_TITLE			70100	//音频输入
#define		ID_STR_CFG_AUDIO_INPUT_MIC_IN			70101	//麦克输入
#define		ID_STR_CFG_AUDIO_INPUT_LINE_IN			70102	//线性输入

#define		ID_STR_CFG_AUDIO_CAP_TITLE				70120	//音频输出
#define		ID_STR_CFG_AUDIO_CAPTURE				70121	//采集音频
#define		ID_STR_CFG_AUDIO_CAP_FORMAT				70122	//音频格式

#define		ID_STR_CFG_VIDEO_TITLE					70140	//视频参数
#define		ID_STR_CFG_VIDEO_VBR					70141	//可变码率
#define		ID_STR_CFG_VIDEO_CBR					70142	//固定码率
#define		ID_STR_CFG_VIDEO_CODE_RATE				70143	//码率
#define		ID_STR_CFG_VIDEO_I_FRAME_SPACE			70144	//主帧间隔
#define		ID_STR_CFG_VIDEO_FRAME_RATE				70145	//帧率
#define		ID_STR_CFG_VIDEO_CODE_CONTROL			70146	//视频编码控制
#define		ID_STR_CFG_VIDEO_CODE_QUALITY			70147	//视频编码质量
#define		ID_STR_CFG_VIDEO_QUALITY_TIP			70148	//(值越小，图像质量越好，码流控制幅度越大)


#define		ID_STR_CFG_PTZ_TITLE					70160	//云台参数
#define		ID_STR_CFG_PTZ_CODE						70161	//协议码
#define		ID_STR_CFG_PTZ_PROTOCOL					70162	//协议
#define		ID_STR_CFG_PTZ_BAUDRATE					70163	//波特率
#define		ID_STR_CFG_PTZ_DATA_BIT					70164	//数据位
#define		ID_STR_CFG_PTZ_STOP_BIT					70165	//停止位
#define		ID_STR_CFG_PTZ_CHECK_BIT				70166	//校验
#define		ID_STR_CFG_PTZ_CHECK_NONE				70167	//无
#define		ID_STR_CFG_PTZ_CHECK_ODD				70168	//奇校验
#define		ID_STR_CFG_PTZ_CHECK_EVEN				70169	//偶校验


#endif