//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by clientdemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENTDEMO_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_DLG_PREVIEW                 130
#define IDD_DIALOG_QUERY                131
#define IDD_DIALOG_TRACK_BACK           132
#define IDD_DIALOG_TRANS_PARAM          134
#define IDD_DIALOG_GET_DEV_IP           135
#define IDD_DLG_DEVLIST                 136
#define IDD_DIALOG_PLAYBACK             137
#define IDD_DIALOG_SN                   138
#define IDR_RCLICKMENU                  139
#define IDD_DLG_PTZ                     140
#define IDD_DLG_PARAM_CONFIG            141
#define IDD_DLG_SNAPSHOT                176
#define IDD_DLG_PARAMER_CONFIG          214
#define IDD_DLG_REC_PLAYBACK            340
#define IDD_DLG_REC_PLAYBACK_CONTROL    341
#define IDD_DLG_PLAY                    342
#define IDC_LOADING_STC_TIP             342
#define IDD_DIALOG_TRANS_DATA           343
#define IDD_DIALOG_SEND_FILE_TO_DEV     373
#define IDD_DLG_LOADING                 374
#define IDC_EDIT_USER                   1000
#define IDC_ST_VIDEO                    1000
#define IDC_EDIT_FILE_PATH              1000
#define IDC_EDIT_PSW                    1001
#define IDC_TREE_DEV                    1001
#define IDC_COMBO_CHANNEL               1001
#define IDC_EDIT_IP                     1002
#define IDC_COMBO_MODE                  1002
#define IDC_COMBO_FINGERPRINT_CHECKED   1002
#define IDC_STATIC_MSG                  1003
#define IDC_BTN_PAUSE                   1003
#define IDC_COMBO_FACE_CHECKED          1003
#define IDC_LIST_GPS                    1004
#define IDC_BUTTON_PLAY                 1004
#define IDC_BTN_STOP                    1004
#define IDC_BTN_FILE_DOWN               1004
#define IDC_BUT_SAVE_MUT                1004
#define IDC_EDIT_DEV_IDNO               1005
#define IDC_BTN_SLOW                    1005
#define IDC_BUT_SAVE                    1005
#define IDC_COMBO_SEARCH_CHANNEL        1006
#define IDC_BUTTON_STOP                 1006
#define IDC_BUTTON_FROWARD_I_FRAM       1006
#define IDC_COMBO_LOCATION              1007
#define IDC_BTN_STEP                    1007
#define IDC_LIST_FILE                   1008
#define IDC_BUTTON_SEARCH               1009
#define IDC_COMBO_FILE_TYPE             1010
#define IDC_COMBO_FILE_ATTRIBUTE        1011
#define IDC_DATETIMEPICKER_SEARCH_TIME  1012
#define IDC_LIST_ALARM                  1013
#define IDC_DATETIMEPICKER_SEARCH_TIME2 1013
#define IDC_LIST_USER_LOG               1014
#define IDC_BUTTON_USER_LOG_QUERY       1015
#define IDC_BUTTON_SOUND                1015
#define IDC_BUTTON_ALARM_LOG_QUERY      1016
#define IDC_BUTTON_QUERY                1016
#define IDC_BTN_PLAY                    1016
#define IDD_DLG_AUE_CHECKED_SETUP       1016
#define IDC_SLIDER1                     1017
#define IDC_DATE_BEG                    1018
#define IDC_BTN_OPEN                    1018
#define IDD_DLG_AUE_WIFI_SETUP          1018
#define IDC_TIME_BEG                    1019
#define IDC_ST_TIME                     1019
#define IDD_DLG_AUE_ALCOHOL_SETUP       1019
#define IDC_DATE_END                    1020
#define IDC_ST_RATE                     1020
#define IDD_DLG_AUE_COORDINATE_SETUP    1020
#define IDC_TIME_END                    1021
#define IDC_CHK_SOUND                   1021
#define IDC_COMBO_ALARM_TYPE            1022
#define IDC_SLIDER2                     1022
#define IDC_COMBO_USER                  1023
#define IDC_BUTTON_USER                 1024
#define IDC_STATIC_USER_LOG_COUNT       1025
#define IDC_STATIC_ALARM_LOG_COUNT      1026
#define IDC_STATIC_TIP                  1027
#define IDC_BUTTON_GET_COLORE           1028
#define IDC_BUTTON_SET_COLORE           1029
#define IDC_COMBO_DEV_IDNO              1030
#define IDC_BTN_FAST                    1030
#define IDC_LIST_TRACK                  1031
#define IDC_BUTTON_BACKWARD_I_FRAM      1031
#define IDC_STATIC_DEV                  1032
#define IDC_LIST_TPD                    1032
#define IDC_DT_DATE_BEGIN               1033
#define IDC_BUTTON_TPD                  1033
#define IDC_DT_TIME_BEG                 1034
#define IDC_DT_TIME_END                 1035
#define IDC_COMBO_MP                    1036
#define IDC_STATIC_TPD_COUNT            1036
#define IDC_EDIT_PARKING_TIME           1037
#define IDC_BUTTON_TRACK_BACK           1038
#define IDC_EDIT_SET_SEND               1039
#define IDC_EDIT_SET_REC                1041
#define IDC_LIST                        1041
#define IDC_BUTTON_SET                  1043
#define IDC_COMBO_DEV                   1044
#define IDC_BUTTON_TRANS_PARAM          1045
#define IDC_LIST_DEV_IP                 1046
#define IDC_BUTTON_GET_DEV_IP           1046
#define IDC_BUTTON_SEL_DEV              1047
#define IDC_TREE_ENC                    1048
#define IDC_COMBO_TPD                   1049
#define IDC_BUTTON_GET_SNAPSHOT         1050
#define IDC_BUTTON_SET_SNAPSHOT         1051
#define IDC_BTN_SAVE                    1051
#define IDC_BUTTON_DOWN                 1052
#define IDC_BUTTON_PLAYBACK             1053
#define IDC_SLIDER_VOL                  1054
#define IDC_BUTTON_CLEAR_ALARM          1056
#define IDC_BUTTON_PLAY_FILE            1057
#define IDC_BUTTON_AUE_CHECKED          1057
#define IDC_BUTTON_DEVICE_LOG_SERACH    1059
#define IDC_BUTTON_START_SNAPSHOT_TIMER 1060
#define IDC_BUTTON_ADD_SNAPSHOT         1060
#define IDC_BUTTON_AUE_WIFI             1060
#define IDC_BUTTON_STOP_SNAPSHOT_TIMER  1061
#define IDC_BUTTON_AUE_ALCOHOL          1061
#define IDC_ST_DOWNLOAD                 1062
#define IDC_BTN_READ_STATUS             1063
#define IDC_BUTTON_DEL_SNAPSHOT         1064
#define IDC_BTN_PTZ_FUNC                1065
#define IDC_BTN_FUNC_PTZ                1065
#define IDC_BUTTON_TRANCE_SVR           1066
#define IDC_LIST_LOG                    1067
#define IDC_ST_CHANNEL                  1067
#define IDC_BUTTON_RESUME_DOWN          1068
#define IDC_ST_MODE                     1068
#define IDC_ST_FINGERPRINT_CHECKED      1068
#define IDC_STATIC_TIME                 1069
#define IDC_BTN_PARAM_CONFIG            1069
#define IDC_ST_FACE_CHECKED             1069
#define IDC_BUTTON_ADD_SN               1070
#define IDC_BUTTON2                     1071
#define IDC_BUTTON_DEL_SN               1071
#define IDC_ST_PIC                      1071
#define IDC_BUTTON_SNAPSHOT             1072
#define IDC_BUTTON1                     1073
#define IDC_BUTTON_SN                   1073
#define IDC_BUTTON_AUDIO_START          1073
#define IDC_BTN_PTZ1                    1073
#define IDC_BTN_PARAM_FILE_GET          1073
#define IDC_BTN_GET_PARAM               1073
#define IDC_EDIT1                       1074
#define IDC_SNAPSHOT_PATH               1074
#define IDC_BTN_PTZ2                    1074
#define IDC_BTN_PARAM_FILE_UPDATE       1074
#define IDC_BTN_SET_PARAM               1074
#define IDC_COMBO_AUDIO                 1075
#define IDC_BTN_PTZ3                    1075
#define IDC_BTN_PARAM_FILE_SET          1075
#define IDC_BUTTON3                     1076
#define IDC_BUTTON_AUDIO_STOP           1076
#define IDC_BTN_PTZ4                    1076
#define IDC_BTN_PARAM_FILE_CLOSE        1076
#define IDC_BTN_PTZ5                    1077
#define IDC_BTN_PTZ6                    1078
#define IDC_BTN_PTZ7                    1079
#define IDC_BTN_PTZ8                    1080
#define IDC_BTN_PTZ9                    1081
#define IDC_BTN_PTZ10                   1082
#define IDC_BTN_PTZ11                   1083
#define IDC_BTN_PTZ12                   1084
#define IDC_BTN_PTZ13                   1085
#define IDC_BTN_PTZ14                   1086
#define IDC_BTN_PTZ15                   1087
#define IDC_BTN_PTZ_LIGHT_OPEN          1088
#define IDC_BTN_PTZ_LIGHT_CLOSE         1089
#define IDC_BUT_EXPORT                  1089
#define IDC_BTN_PTZ_WIPER_OPEN          1090
#define IDC_BUT_IMPORT                  1090
#define IDC_BTN_PTZ19                   1091
#define IDC_BTN_PTZ_WIPER_CLOSE         1092
#define IDC_BUTTON_I_FRAME              1093
#define IDC_ED_POINT                    1094
#define IDC_BTN_CAPTURE                 1095
#define IDC_BTN_PTZ_MOVE                1096
#define IDC_BTN_PTZ_SET                 1097
#define IDC_BTN_PTZ_DEL                 1098
#define IDC_ED_SSID                     1098
#define IDC_BTN_BROWSE                  1099
#define IDC_ED_PASSWORD                 1099
#define IDC_CHK_PREVIEW_RECORD          1101
#define IDC_BTN_OPEN_RECORD_PATH        1103
#define IDC_ED_TIP                      1104
#define IDC_ST_SSID                     1104
#define IDC_GROUP_CHECKED               1106
#define IDC_GROUP_WIFI2                 1107
#define IDC_ST_PASSWORD                 1108
#define IDC_STATIC_UPLOAD_FILE          1163
#define IDC_ST_THRESHOLD                1164
#define IDC_ED_THRESHOLD                1165
#define IDC_ST_ALCOHOL                  1166
#define IDC_ED_ALCOHOL                  1167
#define IDC_GROUP_ALCOHOL               1168
#define IDC_ST_ALCOHOL_CHECKED          1169
#define IDC_ST_READ_TIP                 1170
#define IDC_COMBO_ALCOHOL_CHECKED       1170
#define IDC_ST_MAPTYPE                  1171
#define IDC_COMBO_MAPTYPE               1172
#define IDC_ST_JINGDU                   1173
#define IDC_ED_JINGDU                   1174
#define IDC_ED_WEIDU                    1175
#define IDC_ST_WEIDU                    1176
#define IDC_BTN_OK                      1177
#define IDC_ST_PARAMER_MAIN             1198
#define IDC_STATIC_TELL                 1201
#define IDC_LOADING_STC_GIF             1439
#define IDC_SLIDER_TIME                 1442
#define IDC_STATIC_VOLUME               1444
#define IDC_STATIC_FILE_TYPE            1477
#define IDC_STATIC_FILE_TYPE_TIP        1506
#define ID_MAIN_FRONT                   32771
#define ID_MENU_RECORD_START            32772
#define ID_MENU_RECORD_STOP             32773
#define ID_MENU_MAIN_FRONT              32774
#define ID_MAIN_32775                   32775
#define ID_MENU_SEND_FILE               32776
#define ID_MAIN_32777                   32777
#define ID_MENU_PARAMER_CONFIG          32778
#define ID_MAIN_32779                   32779
#define ID_MENU_COORDINATE              32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
