#ifndef _USR_LOG_DEF_H_
#define _USR_LOG_DEF_H_


#define	USRLOG_DEVICE_NULL						""	//空设备定义
#define	USRLOG_USER_NULL						0	//用户数据为空定义

//用户操作日志定义
#define	USRLOG_MAIN_TYPE_LOGIN					1	//客户端登录
#define	USRLOG_MAIN_TYPE_DEVICE_CTRL			2	//设备控制指令	
#define	USRLOG_MAIN_TYPE_MEDIA					3	//媒体业务

//客户端登录
#define	USRLOG_LOGIN_SUB_TYPE_LOGIN				1	//客户端登录（登录地址，会话编号，登录类型(1客户端，3iphone客户端，2web客户端)）
#define	USRLOG_LOGIN_SUB_TYPE_LOGOUT			2	//客户端退出
#define	USRLOG_LOGIN_SUB_TYPE_INTERUPT			3	//客户端中断
#define USRLOG_LOGIN_SUB_TYPE_TRANSFER			4	//客户端中转//向LoginSvr注册时由LoginSvr产生
#define USRLOG_LOGIN_SUB_TYPE_UNKOWN_USR		5	//未知用户名和密码信息	（登录地址，账号，密码）
#define USRLOG_LOGIN_SUB_TYPE_GET_SVR_FAILED	6	//分配服务器信息失败

//设备控制
#define	USRLOG_DEV_CTRL_SUB_TYPE_SEND_TEXT		1	//发送TTX指令
#define	USRLOG_DEV_CTRL_SUB_TYPE_SEND_SMS		2	//发送短信息到设备
#define	USRLOG_DEV_CTRL_SUB_TYPE_SEND_CTRL		3	//发送控制指令（断油、断电）
#define	USRLOG_DEV_CTRL_SUB_TYPE_SEND_PTZ		4	//云台控制
#define	USRLOG_DEV_CTRL_SUB_TYPE_READ_STATUS	5	//获取车辆状态
#define USRLOG_DEV_CTRL_SUB_TYP_SET_GPSINTERVAL	6	//设置GPS时间间隔
#define USRLOG_DEV_CTRL_SUB_TYPE_READ_MOTION	7	//获取移动侦测参数
#define USRLOG_DEV_CTRL_SUB_TYPE_SET_MOTION		8	//设置移动侦测参数
#define USRLOG_DEV_CTRL_SUB_TYPE_READ_NETFLOW_STATISTICS	9	//获取网络流量信息
#define USRLOG_DEV_CTRL_SUB_TYPE_SET_NETFLOW_PARAM			10	//配置网络流量参数
#define USRLOG_DEV_CTRL_SUB_TYPE_CLEAR_NETFLOW_STATISTICS	11	//清空网络流量统计
#define USRLOG_DEV_CTRL_SUB_TYPE_ADJUST_NETFLOW_STATISTICS	12	//校正网络流量统计
#define USRLOG_DEV_CTRL_SUB_TYPE_SEND_DISPATCH_COMMAND		13	//下发调度指令
#define USRLOG_DEV_CTRL_SUB_TYPE_SEND_CFG_VIDEO_COMMAND		14	//配置视频参数
#define USRLOG_DEV_CTRL_SUB_TYPE_GET_CFG_VIDEO_COMMAND		15	//获取视频参数
#define USRLOG_DEV_CTRL_SUB_TYPE_SEND_CFG_AUDIO_COMMAND		16	//配置音频参数
#define USRLOG_DEV_CTRL_SUB_TYPE_GET_CFG_AUDIO_COMMAND		17	//获取音频参数
#define USRLOG_DEV_CTRL_SUB_TYPE_SEND_CFG_AUDIO_INPUT_COMMAND		18	//配置音频输入参数
#define USRLOG_DEV_CTRL_SUB_TYPE_GET_CFG_AUDIO_INPUT_COMMAND		19	//获取音频输入参数
#define USRLOG_DEV_CTRL_SUB_TYPE_SEND_CFG_PTZ_COMMAND		20	//配置云台参数
#define USRLOG_DEV_CTRL_SUB_TYPE_GET_CFG_PTZ_COMMAND		21	//获取云台参数
#define USRLOG_DEV_CTRL_SUB_TYPE_GET_PARAM					22	//获取参数
#define USRLOG_DEV_CTRL_SUB_TYPE_SET_PARAM					23	//配置参数
#define USRLOG_DEV_CTRL_SUB_TYPE_TRANSPARENT_CONFIG			24	//配置参数
#define	USRLOG_DEV_CTRL_SUB_TYPE_FREE_PRESET_GET			25	//获取空闲预置位
#define	USRLOG_DEV_CTRL_SUB_TYPE_GET_VIDEO_COLOR			26	//设置视频颜色
#define	USRLOG_DEV_CTRL_SUB_TYPE_SET_VIDEO_COLOR			27	//获取视频颜色

//媒体业务，由流媒体服务器写媒体日志（开始和停止时都记录日志信息）
#define	USRLOG_MEDIA_SUB_TYPE_VIDEO					1	//视频预览（通道，类型）
#define	USRLOG_MEDIA_SUB_TYPE_AUDIO					2	//音频监听（通道）
#define	USRLOG_MEDIA_SUB_TYPE_TACKBACK				3	//双向对讲
#define	USRLOG_MEDIA_SUB_TYPE_SNAPSHOT				4	//图片抓拍
#define	USRLOG_MEDIA_SUB_TYPE_REC_SEARCH			5	//录像搜索（通道，类型，时间）
#define	USRLOG_MEDIA_SUB_TYPE_REC_DOWN				6	//录像下载（录像文件）
#define	USRLOG_MEDIA_SUB_TYPE_DLOWN_DEV_PARAM		7	//获取设备参数
#define	USRLOG_MEDIA_SUB_TYPE_UPLOAD_DEV_PARAM_FILE	8	//上传设备参数文件
#define	USRLOG_MEDIA_SUB_TYPE_UPLOAD_DEVICE_PARAM	9	//上传设备参数
#define	USRLOG_MEDIA_SUB_TYPE_UPLOAD_DEV_UP_FILE	10	//上传设备升级文件（升级文件版本）
#define	USRLOG_MEDIA_SUB_TYPE_UPLOAD_UPGRADE_DEVICE	11	//设备远程升级
#define	USRLOG_MEDIA_SUB_TYPE_PLAYBACK				12	//远程回放
#define	USRLOG_MEDIA_SUB_TYPE_BROADCAST				13	//广播

#endif